### ISSUE TITLE
Feat: Data Space governance – Datasets Management Tabs

### ISSUE THREAD

**Issue by Gab-pm** [okp4/dataverse-portal#106]
# Feature: Data Space governance – Datasets Management Tabs

> **As a** user of the Data Space,
> **I want** to explore the different Datasets Management tabs 
> **So that** I read the terms and conditions of this section

### Scenario 1: default display (desktop)

**Given that** I am a user of the web portal (unauthenticated or authenticated) on the Data Space governance page,
**And** I am using a desktop device,
**When** I am on the Datasets Management section 
**Then** I should see a proper description of the different tabs that appear as presented in the mockup below

### Scenario 2: Mobile Display

**Given that** I am a user of the web portal (authenticated or unauthenticated),
**And** I use a mobile device
**When** I am on the Datasets Management section
**Then** I should see a mobile friendly display (See mock up)

### Scenario 3: Change tab

**Given that** I am a user of the web portal (authenticated or unauthenticated),
**When** the selected tab is Reference, Modify, Dereference or Download
**Then** the adequate selected tab should be displayed (See mock up)

### Scenario 4: Internationalization

**Given that** I am a user of the web portal (authenticated or unauthenticated),
**When** the selected language is English, French, or German
**Then** tab title should be displayed in the adequate selected language (See config)

En
> Reference
> Modify
> Dereference
> Download

Fr
> Référencer
> Modifier
> Déréférencer
> Télécharger

De
> Referenzieren
> Bearbeiten
> Auslisten
> Herunterladen

## Requirements

1. Default landing tab is Reference

#### Desktop

![image.png](https://images.zenhubusercontent.com/63578bc0de26436874ae0864/aba51097-171c-4e80-a9e7-11526a81e73c)

#### Mobile

![image.png](https://images.zenhubusercontent.com/63578bc0de26436874ae0864/08714d41-168f-4d02-9549-d9b3b0f1d414)

### Environment

- staging URL: <https://app.staging.okp4.network/>

## Additional informations

None.

**Comment by lolottetheclash** [comment]
@MdechampG should we consider implementing some subroutes when clicking on a section (like: datasets management)?
