### ISSUE TITLE
create Dataverse card component

### ISSUE THREAD

**Issue by AnjaMis** [okp4/dataverse-portal#116]
# Dataverse card component

## To do

Create dataverse card component that will be used for the Dataverse catalog page and the Explore block on the homepage

## Acceptance criteria

- [x] a functional component 
- [x] matches the design requirements
- [x] can be used with different props on other pages 

- staging URL: <https://app.staging.okp4.network/>

## Additional informations

None.

**Comment by fredericvilcot** [comment]
@lolottetheclash 
I close this issue as it does not respect the criteria to specify a feature.
I let you create the feature based upon dedicated template.
Thx 🙏
