### ISSUE TITLE
Enhancement : App - fix sidebar & toolbar

### ISSUE THREAD

**Issue by ErikssonJoakim** [okp4/dataverse-portal#117]
# Feature: Enhancement : App - fix sidebar & toolbar
> **As a**  desktop, tablet and mobile user of the Portal,
> **I want** to have easy access to the app sidebar & toolbar when navigating the application
> **So that** I don't have to scroll through long pages to access the sidebar & toolbar

### Scenario: all displays
**Given that** I am a desktop, tablet and mobile user of the Portal,,
**When** when I scroll through a page in any navigation item,
**Then** the sidebar & toolbar should be fixed when I scroll down / up
**So that** I always have access to menus at any time and anywhere in the app

## Requirements
This issue is easily testable on the Dataverse page, as it contains a large number of elements. 
We must be able to scroll the whole page to see all the cards, the size of the sidebar is the same as the screen without scroll inside, and the toolbar remains visible. 

### Environment

* staging URL: <https://app.staging.okp4.network/>

## Additional informations
None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206527953) by [Unito](https://www.unito.io)

**Comment by fredericvilcot** [comment]
@MdechampG 
FYI

**Comment by MdechampG** [comment]
Test 23/03

Desktop : Safari, Firefox, Chrome
Mobile : Safari
Tablet (with desktop) : Firefox

Scenario : all displays OK ✅ 

❌ When the screen is not high enough, we can't see the bottom of the bar as we can't scroll the lateral bar. 

<img width="1522" alt="image" src="https://user-images.githubusercontent.com/92780073/227256406-9b73057f-c4b8-4172-8f0b-0c3d9479173e.png">

**Comment by fredericvilcot** [comment]
@ErikssonJoakim 
Please, could you take care of this issue?
Thx

**Comment by ErikssonJoakim** [comment]
@fredericvilcot Yes I will look into it 🙂

**Comment by MdechampG** [comment]
@ErikssonJoakim is it linked to the #132  ?

**Comment by ErikssonJoakim** [comment]
@MdechampG No I've just merged a fix for the problem that you described above. #132 will be to test a part

**Comment by MdechampG** [comment]
Thank you @ErikssonJoakim !

Test 28/03

Desktop : Safari, Firefox, Chrome
Mobile : Safari
Tablet (with desktop) : Firefox

Scenario : all displays OK ✅
