### ISSUE TITLE
Feat: details Page - General Metadata and audit metadata

### ISSUE THREAD

**Issue by MdechampG** [okp4/dataverse-portal#120]
# Feature: details page - General Metadata and audit metadata
> **As a**  user of the portal,
> **I want** to read general and audit metadata of a Dataverse item
> **So that** I can understand better what is the item and its properties.

### Scenario: default display (desktop)
**Given that** I am a user of the web portal (authenticated or unauthenticated),
**When** I am on the detail page of a dataverse item, 
**And** I use a _desktop device_
**Then** I should see the general and audit metadata of the item (See mock up)

For each resource a specific list of properties is to be displayed. 
| Service             | Service Description                                                                                                      | Service Type   |
|---------------------|---------------------------------------------------------------------------------------------------------------------------|-----------------|
| **Core Metadata**   |                                                                                                                           |                 |
| Identifier          | A decentralized identifier URI is a URI that identifies a subject in a decentralized system and is managed independently of any centralized registry. | anyURI          |
| Registrar           | References the individual, company, or organization that is responsible for registering and managing a resource.         | DIDURI          |
| **General Metadata**|                                                                                                                           |                 |
| Category            | A category of the resource.                                                                                               | Concept         |
| Publisher           | An entity primarily responsible for making the resource available.                                                        | string          |
| Tag                 | A keyword or term assigned to the resource.                                                                               | string          |
| Title               | A name given to the resource.                                                                                             | string          |
| Description         | A human-readable description of the resource.                                                                             | string          |
| **Audit Metadata**  |                                                                                                                           |                 |
| Created on          | The date and time when the resource was created.                                                                         | dateTime        |
| Created by          | The entity who created the resource.                                                                                     | DIDURI          |
| Last modified on    | The date and time when the resource was last modified.                                                                    | dateTime        |
| Last modified by    | The entity who last modified the resource.                                                                               | DIDURI          |

| Dataset             | Dataset Description                                                                                                      | Dataset Type    |
|----|----|----|
|**Core Metadata**|||
| Identifier          | A decentralized identifier URI is a URI that identifies a subject in a decentralized system and is managed independently of any centralized registry. | anyURI          |
| Registrar           | References the individual, company, or organization that is responsible for registering and managing a resource.         | DIDURI          |
| Provided by         | References the entity that provides the resource.                                                                        | anyURI          |
|**General Metadata**|||
| Publisher           | An entity primarily responsible for making the resource available.                                                        | string          |
| Creator             | An entity primarily responsible for making the resource.                                                                  | string          |
| Tag                 | A keyword or term assigned to the resource.                                                                               | string          |
| Title               | A name given to the resource.                                                                                             | string          |
| Description         | A human-readable description of the resource.                                                                             | string          |
| Spatial coverage    | The spatial applicability of the resource.                                                                               | Concept         |
| License             | A legal document giving official permission to do something with the resource.                                          | Concept         |
| Topic               | A topic of the resource.                                                                                                 | Concept         |
| Format              | The format of the resource.                                                                                              | Concept         |
| Temporal coverage   | The temporal applicability of the resource.                                                                              | Period          |
|**Audit Metadata**|||
| Created on          | The date and time when the resource was created.                                                                         | dateTime        |
| Created by          | The entity who created the resource.                                                                                     | DIDURI          |
| Last modified on    | The date and time when the resource was last modified.                                                                    | dateTime        |
| Last modified by    | The entity who last modified the resource.                                                                               | DIDURI          |

| Zone                | Zone Description                                                                                                         | Zone Type       |
|----|----|----|
|**Core Metadata**|||
| Identifier          | A decentralized identifier URI is a URI that identifies a subject in a decentralized system and is managed independently of any centralized registry. | anyURI          |
| Registrar           | References the individual, company, or organization that is responsible for registering and managing a resource.         | DIDURI          |
|**General Metadata**|||
| Publisher           | An entity primarily responsible for making the resource available.                                                        | string          |
| Tag                 | A keyword or term assigned to the resource.                                                                               | string          |
| Title               | A name given to the resource.                                                                                             | string          |
| Description         | A human-readable description of the resource.                                                                             | string          |
| Topic               | A topic of the resource.                                                                                                 | Concept         |
|**Audit Metadata**|||
| Created on          | The date and time when the resource was created.                                                                         | dateTime        |
| Created by          | The entity who created the resource.                                                                                     | DIDURI          |
| Last modified on    | The date and time when the resource was last modified.                                                                    | dateTime        |
| Last modified by    | The entity who last modified the resource.                                                                               | DIDURI          |

### Scenario: mobile display 
**Given that** I am a user of the web portal (authenticated or unauthenticated),
**When** I am on the detail page of a dataverse item, 
**And** I use a _mobile device_
**Then** I should see the general metadata of the item on its mobile version (See mock up)
See previous table for the properties to display

### Scenario : Copy DID
**Given that** I am on the Detail Page of a dataverse item,
**When** I click on the logo located next to a DID (public key),
**Then** the DID is copied in the clipboard
**And** a toast appears with `copied` and a tick 

### Scenario: Internationalization
**Given that**I am a user of the web portal (authenticated or unauthenticated),
**When** the selected language is English
**Then** texts should be displayed in English language,
`Publisher`
`Registrar`
`Provided by`
`Belong to`
`Unique ID`
`Metadata created by`
`Metadata created on`
`Metadata last modified by`
`Metadata last modified on`
`Copy`

**And** metadata of the resources should be displayed in English

**Given that** I am a user of the web portal on the home page,
**When** the selected language is French
**Then** texts should be displayed in French language,
`Éditeur`
`Enregistré par`
`Fourni par`
`Appartient à`
`ID unique`
`Métadonnées créées par `
`Métadonnées créées le`
`Dernière modification des métadonnées par`
`Dernière modification des métadonnées le`
`Copié`
**And** metadata of the resources should be displayed in French 

**Given that** I am a user of the web portal on the home page,
**When** the selected language is German
**Then** texts should be displayed in German language,
`Verleger`
`Registrar`
`Bereitgestellt von`
`Zugehörig zu`
`Einzigartige ID`
`Metadaten erstellt von`
`Metadaten erstellt am`
`Metadaten zuletzt geändert von`
`Metadaten zuletzt geändert am`
`Kopiert`
**And** metadata of the resources should be displayed in German

#### Desktop 
Data Space
![](https://user-images.githubusercontent.com/92780073/231457773-a13f5035-4205-4a9d-af76-5fe006772176.png)

Dataset

![](https://user-images.githubusercontent.com/92780073/231457886-4ab0cb97-549b-4540-ba86-a064784dd022.png)

Service 

![](https://user-images.githubusercontent.com/92780073/231457958-47d4afda-cc89-4fd0-88ec-1dd46f86cb40.png)

#### Mobile
Data Space

![](https://user-images.githubusercontent.com/92780073/231458249-73869210-7c69-4ab1-ae6c-6678a0418075.png)

Dataset
![](https://user-images.githubusercontent.com/92780073/231458181-9f97eae9-e5e8-4af7-81c8-48b2751918ca.png)

Service (without provided by -> Mock up to be updated)

![](https://user-images.githubusercontent.com/92780073/231458096-3ea33ed9-fcec-4f39-9414-4119d20e9861.png)

### Environment

* staging URL: <https://app.staging.okp4.network/>

## Additional informations
None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206527989) by [Unito](https://www.unito.io)

**Comment by lolottetheclash** [comment]
@MdechampG this feature also contain the fact that a user can copy the text value by clicking on the right icon, right? Because it's not mentioned in requirements.

**Comment by GeoffreyPicard** [comment]
I need to know how I will receive the data and the type of the data

**Comment by lolottetheclash** [comment]
`Copy` text must be updated into `Copied` and translated.

**Comment by MdechampG** [comment]
This issue now is related to all Dataverse items (not only resources)

**Comment by lolottetheclash** [comment]
Updates:
- Unique ID must be displayed for dataspace too
- when a user copied a data by clicking on the copy/paste icon, a toast must appear at bottom right of the page to indicate to the user that its text has been correctly copied.
