### ISSUE TITLE
Dataverse cards loading

### ISSUE THREAD

**Issue by lolottetheclash** [okp4/dataverse-portal#150]
# Feature: Dataverse items loading
> **As a** user of the portal,
> **I want** to see some cards skeleton animation
> **When** I arrive on the explore Dataverse page
> **So that** I understand that my action is taken into account and that the content is loading

### Scenario 1 : default display (desktop)
**Given that** I am a user of the web portal (unauthenticated or authenticated),
**And** I am using a _desktop_ device,
**When** I am on the explore Dataverse page 
**Then** I should see 9 animated skeleton cards if data are not ready to be displayed

### Scenario 2 : Tablet display 
**Given that** I am a user of the web portal (unauthenticated or authenticated),
**And** I am using a _tablet_ device,
**When** I am on the explore Dataverse page 
**Then** I should see 8 animated  skeleton cards if data are not ready to be displayed

### Scenario 3 : Mobile Display
**Given that** I am a user of the web portal (unauthenticated or authenticated),
**And** I am using a _mobile_ device,
**When** I am on the explore Dataverse page 
**Then** I should see 2 animated skeleton cards if data are not ready to be displayed

### Mockups
Here is an example of inspiration, knowing that we will have to get as close as possible to our current card:

![Capture d’écran 2023-03-31 à 11.04.45.png](https://images.zenhubusercontent.com/62aa0d2704bd8f5167ff33b3/b14390dc-1a1f-43a1-85c2-e54405a3850d)

### Environment

* staging URL: <https://app.staging.okp4.network/>

## Additional informations
To implement from scratch, no library should be used.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206528362) by [Unito](https://www.unito.io)

**Comment by GeoffreyPicard** [comment]
We can make a component Skeleton for the component folder.
With some properties like rouded, rectangular, circular...

Like this exemple from MUI:
https://mui.com/material-ui/react-skeleton/

**Comment by MdechampG** [comment]
Hello ! Could you tell me how I can test it without the ontological database ?

**Comment by 0xLodz** [comment]
> Hello ! Could you tell me how I can test it without the ontological database ?

Hey! I discussed with @lolottetheclash about that. The code has been validated by the tech team but we won't test it until we fetch some data from the ontology.

**Comment by MdechampG** [comment]
Ok thank you !

**Comment by ChaimaaZaoui** [comment]
Tested on Mozilla, Windows desktop => Success 
Couldn't test on Iphone Safari, I don't know how to generate the loading.

**Comment by 0xLodz** [comment]
I was able to test on Safari from an Iphone on the dataverse (explorer) page:
<img width="419" alt="image" src="https://github.com/okp4/dataverse-portal/assets/8344874/9a6393c8-ff53-4f16-9db1-582ad3fa7303">

**Comment by ChaimaaZaoui** [comment]
Thanks @0xLodz
