### ISSUE TITLE
Feat: Large screen page content display

### ISSUE THREAD

**Issue by lolottetheclash** [okp4/dataverse-portal#151]
# Feature: Large screen page content display
> **As a** user of the portal,
> **I want** to see unstreched page content
> **When** I am displaying the app on a large screen
> **So that** I enjoy my user experience better

### Scenario 1 : large screen 
**Given that** I am a user of the web portal (unauthenticated or authenticated),
**And** I am using a large _desktop_ device,
**When** I am on any page
**Then** I should see the page content width limited and displayed on the left side of the screen

### Mockups
What we have now: 

![Capture d’écran 2023-03-31 à 11 18 53](https://user-images.githubusercontent.com/35332974/229080163-519fed31-f84f-478f-a110-b4cae09f9640.png)

What we should have:

![Capture d’écran 2023-03-31 à 11 19 12](https://user-images.githubusercontent.com/35332974/229080183-ef2926ee-39db-4a17-b2e7-3340e1c40a12.png)

* staging URL: <https://app.staging.okp4.network/>

## Additional informations
None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206528607) by [Unito](https://www.unito.io)

**Comment by MdechampG** [comment]
Test 04/03
Firefox and Chrome 

Scenario : large screen ✅
