### ISSUE TITLE
Feat : Details page - Temporal coverage  

### ISSUE THREAD

**Issue by MdechampG** [okp4/dataverse-portal#169]
# Feature: Details page - Temporal coverage  

> **As a** User of the portal on the details page of a dataset,
> **I want** to read the temporal coverage of the dataset 
> **So that** I easily understand the context of this dataset

### Scenario: General display

**Given that** I am a user of the web portal on the detail page of a dataset,
**And** I am using any device,
**When** the `Start date` and `End date` of a dataset are filled out, 
**Then** I should see From `Start date` + To `End date` displayed on 2 lines (mock up 1) 
**When** only the `Start date` of a dataset is filled out, 
**Then** I should see From `Start date` (mock up 2) 
**When** only the `End date` of a dataset is filled out, 
**Then** I should see To `End date` (mock up 3) 
**When** there is no date filled out, 
**Then** I should not see Temporal Coverage

### Scenario : Error

**Given that** I am a user of the web portal on the detail page of a dataset,
**And** I am using any device,
**When** the `Start Date` or the `End date` are not filled out correctly (bad format or `Start Date` later than `End Date` for instance) 
**Then** I should see a dash (mock up 4) 

### Scenario : Internationalization

**Given that** I am a user of the web portal on the detail page of a dataset,
**And** the selected language is English
**Then** the date format should be `MM/dd/yyyy` 
**And** texts should be displayed in English
`From`
`To`

**Given that** I am a user of the web portal on the detail page of a dataset,
**And** the selected language is French
**Then** the date format should be `dd/MM/yyyy` 
**And** texts should be displayed in French
`Depuis le`
`Jusqu'au`

**Given that** I am a user of the web portal on the detail page of a dataset,
**And** the selected language is German
**Then** the date format should be `dd.MM.yyyy` 
**And** texts should be displayed in German
`Von`
`Bis`

### Mockups

1 / ![image.png](https://images.zenhubusercontent.com/616e76157d9dbb44e290ed55/d5183102-94da-477f-bb2a-99d709674618)

2/ ![image.png](https://images.zenhubusercontent.com/616e76157d9dbb44e290ed55/164a9cae-e306-4bc1-960d-4f4c11926841)

3/ ![image.png](https://images.zenhubusercontent.com/616e76157d9dbb44e290ed55/5d9281b5-8157-4521-ac45-1fa79d4eb542)

4/ ![image.png](https://images.zenhubusercontent.com/616e76157d9dbb44e290ed55/855bf2d2-c092-4761-983c-cb65f672070b)

### Environment

- staging URL: <https://app.staging.okp4.network/>

## Additional informations

None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206528758) by [Unito](https://www.unito.io)

**Comment by 0xLodz** [comment]
@MdechampG could you confirm me that the german date is `dd.MM.yy`? Or like french and english, the year is display with 4 digits ? `dd.MM.yyyy`? Thanks

**Comment by MdechampG** [comment]
@0xLodz I checked with @lmarline and finally it's not the good format. It should be exactly like for French `dd/MM/yyyy`
I have updated the issue description.

**Comment by 0xLodz** [comment]
Thanks @MdechampG , I also guess that we need french and german translations for "From:" and "To:".
Is "De : " and "À : " for french and "Von : " and "Bis : " for german the most appropriate?
Thanks

**Comment by 0xLodz** [comment]
@lmarline thanks for the clarifications!

@MdechampG it looks weird in french with `De` and `À`.
![image](https://user-images.githubusercontent.com/8344874/231107342-a0d04eab-bfe2-4b71-9e2a-d0b0c472ab85.png)
`Depuis le` and `jusqu'au` seems more appropriate, what do you think?

**Comment by MdechampG** [comment]
@0xLodz I have added the error Start End later than End date in the Scenario Error. 
We should see a dash as well as for the format error.

**Comment by MdechampG** [comment]
Thanks @lmarline for the trad in German ! 

@0xLodz You're right it's better with Depuis / Jusqu'au. 

I add the translations in the issue :)

**Comment by 0xLodz** [comment]
@MdechampG on the mockup we don't have colons. Should we display them? Thanks

**Comment by SpicySalm0n** [comment]
@0xLodz you can show or hide them in the right menu in the "Layout Grid" section by pressing the eye

<img width="1034" alt="Capture d’écran 2023-04-11 à 14 31 11" src="https://user-images.githubusercontent.com/115076387/231163116-5333a4f6-635e-4902-9abe-8dcac0c4a842.png">

**Comment by 0xLodz** [comment]
@SpicySalm0n sorry if I wasn't clear in my previous request. I asked for the colons `:` between From and the date.

![image](https://user-images.githubusercontent.com/8344874/231176561-7d5732d2-ca25-404b-be28-3f4812ed3541.png)

**Comment by SpicySalm0n** [comment]
@0xLodz 
Yes mb I understand "columns" 😅
I updated all the mock-ups!

**Comment by ChaimaaZaoui** [comment]
Test on firefox desktop
- S1 : Executed, only the start and end date both filled is passed, 
- - I need dataset with only a start date, and a dataset with only an end date, and a dataset with no date
- S2 : Not executed
