### ISSUE TITLE
[Error] - Route problem

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#170]
# Feature: Route problem
> **As an** end user navigating the portal ,
> **I want** to be informed if a page has route problem
> **So that** I can reacte accordingly to solve the problem

### Scenario I : default display (desktop / Tablet) 
**Given that** I am an end user navigating the web portal,
**When** I click on a button or link aiming to redirect to a different page
**And** the redirect link has a problem
**Then** I should land on the error page dedicated to the "Route problem"
**And** a text is deplayed on the screen : 
> Sorry,
> we can't find the page you are looking for.
> Try checking the URL or maybe you want to :

**And** 2 buttons are available side to side : 

* `Explore the dataverse`  - `Go to the home page`

### Scenario II : Mobile display
**Given that** I am an end user navigating the web portal,
**When** I click on a button or link aiming to redirect to a different page
**And** the redirect link has a problem
**Then** I should land on the error page dedicated to the "Route problem"
**And** a text is deplayed on the screen : 
> Sorry,
> we can't find the page you are looking for.
> Try checking the URL or maybe you want to :

**And** 2 buttons are available one below the other: 

* `Explore the dataverse`
* `Go to the home page`

### Scenario III : Explore dataverse Button 
**Given that** I am an end user on the of the route problem error page,
**When** I click on `"Explore the dataverse"` button
**Then** I should be redirected to the catalogue page  `.../dataverse `

### Scenario IV : Homepage Button **ENG**
**Given that** I am an end user on the of the route problem error page,
**When** I click on `"Go to the homepage"`  button
**Then** I should be redirected to the portal homepage

### Scenario V: Internalization
Following the selected language, the content on the page is to be displayed accordingly : 

**ENG**

> Sorry,
> we can't find the page you are looking for.
> Try checking the URL or maybe you want to :
> `Explore the dataverse`
> `Go to the home page`

**FR**
> Désolé,
> Nous ne trouvons pas la page que vous avez demandée .
> Vérifiez l'URL ou vous pouvez :
> `Explorer le dataverse`
> `Retourner à l'accueil`

**DE**

> Entschuldigung,
> wir können die Seite, die Sie suchen, nicht finden.
> Versuchen Sie, die URL zu überprüfen, oder vielleicht möchten Sie
> `Das Datenverse erkunden`
> `Zurück zur Startseite`

### Mockups

* **Desktop Dark :**

![image](https://user-images.githubusercontent.com/129745194/233579779-749fd582-9412-4884-aa2c-88d8b15eaef8.png)

* **Desktop Light**
![image](https://user-images.githubusercontent.com/129745194/233579943-318ff26a-3b06-43d8-aea2-60d3d5f9cc33.png)
* *_Tablet Dark / Light *_
![image](https://user-images.githubusercontent.com/129745194/233945415-6a9c3adc-97bf-467e-9b9e-9f5f7c24df35.png)

* **Mobile Dark / Light**
![image](https://user-images.githubusercontent.com/129745194/233945556-f9f5303a-3a88-4173-b019-0560992e675b.png)

### Environment

* staging URL: <https://app.staging.okp4.network/>

## Additional informations
None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206528802) by [Unito](https://www.unito.io)

**Comment by ChaimaaZaoui** [comment]
@AnjaMis the mockups are updated on this US

**Comment by lolottetheclash** [comment]
@AnjaMis @fredericvilcot @ChaimaaZaoui Concerning the test of this ticket, you will have to enter a url which does not exist, for example: https://app.staging.okp4.network/ubuntu 
This page should display our error page.

We will not have to test the rendering of this page with a url that exists, but with a resource that is not found like: 
https://app.staging.okp4.network/dataverse/dataspace/1/governance/toto/titi

This will be treated in a second time because it must be handled differently, and the urls to be tested will be provided on another ticket to facilitate testing by the product team :)
