### ISSUE TITLE
[Error] - Server problem

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#172]
# Feature: Server problem
> **As an** end user navigating the portal ,
> **I want** to know when a server problem is encountered
> **So that** I can reacte accordingly to solve the problem

### Scenario I : Default display (desktop / Tablet)
**Given that** I am an end user navigating the web portal,
**When** I click on a button or link 
**And** a server problem is encountered
**Then** I should receive an error snackbar while staying on my page
**And** a text is displayed on the snackbar : 
> Sorry, something went wrong.
> we are currently unable to handle your request.
> Try to refresh this page.

**And** a button is available on the right hand side of the bar : 

* `Refresh`

### Scenario II : Mobile display 
**Given that** I am an end user navigating the web portal,
**When** I click on a button or link 
**And** a server problem is encountered
**Then** I should receive an error snackbar while staying on my page
**And** a text is displayed on the snackbar : 
> Sorry, something went wrong.
> we are currently unable to handle your request.
> Try to refresh this page.

**And** a button is available below the text : 

* `Refresh`

### Scenario III : Refresh button 
**Given that** I am an end user who received a server error snackbar,
**When** I click on the `Refresh` button
**Then** the browser refreshes the page I am currently in

### Scenario IV : Exit snack bar - Desktop
**Given that** I am an end user who received a server error snackbar
**And** I don't want to refresh the page
**And** I want to close the snackbar 
**When** press the `Exit` button on my keyboard
**Then** the snackbar disappears and I am on the initial page where the problem occurred

### Scenario V : Exit snack bar - Mobile / tablet
**Given that** I am an end user who received a server error snackbar
**And** I don't want to refresh the page
**And** I want to close the snackbar 
**When** click anywhere on the screen outside the snackbar
**Then** the snackbar disappears and I am on the initial page where the problem occurred

### Scenario VI: Internalization
Following the selected language, the content on the page is to be displayed accordingly : 

**ENG**
> Sorry, a problem has occurred.
> We are currently unable to process your request.
> Please try refreshing this page.
> `Refresh`

**FR**
> Désolé, un problème est survenu.
> Nous sommes actuellement incapable de traiter votre demande.
> Essayez de rafraîchir cette page.
> `Actualiser`

**DE**
> Es ist leider ein Problem aufgetreten.
> Wir können Ihre Anfrage derzeit nicht bearbeiten.
> Bitte versuchen Sie, diese Seite zu aktualisieren.
> "Aktualisieren

### Mockups

* **Desktop Dark :**
![image](https://user-images.githubusercontent.com/129745194/233575084-359c924b-b3b2-4b27-b190-d5bb23dfb557.png)

* **Desktop Light**
![image](https://user-images.githubusercontent.com/129745194/233575130-eb013b70-a47b-43e0-b68b-23731e0c72fa.png)
* **Tablet Dark / Light**
![image](https://user-images.githubusercontent.com/129745194/233575219-b540bfc0-cd37-4240-b87d-04109e7f251b.png)

* *_Mobile Dark / Light *_
![image](https://user-images.githubusercontent.com/129745194/233575301-11de3e61-4d04-4bf6-b339-0dd4b4ef0be0.png)

### Environment

* staging URL: <https://app.staging.okp4.network/>

#### Additional details about users specifications

* Snackbar notifications with refresh button must be used only for internal server errors (500), in specific cases like navigating to the `/dataverse` page.
* An action can be proposed to the user, for example refreshing the page with a CTA within the snackbar.
* A Notification for server errors is of the `warning` type. It contains a title, a message, and an action (with CTA).
* Pages like dashboard might contain server requests at component levels; in that case notifications won't be displayed if an errors occurs. We would prefer to opt for a more granular error.
* The system must display only one snackbar if it contains an action (CTA).
* Actions doesn't depend on notifications severity.
### Not implemented suggestion 
* Notifications with larger messages might be displayed longer, depending on message size, with a minimum for eg.  2 seconds and a max of for eg. 7 seconds. [Here is an UX implementation idea](https://ux.stackexchange.com/questions/11203/how-long-should-a-temporary-notification-toast-appear/85898#85898?newreg=729624c7ed2344c0a86b425549e69f6c) (see the 2nd answer of this question).

#### Goal and rules
Define a notification domain at application state level. 

* Any component connected to the state is able to push a notification to the state.
* The notification list component consumes notifications state and display toasts according on notification type (error, warning...) and action (refresh,...).
* The notifications are removed from the state by the user (escape key, click outside), or after a  timer, according to notification action.
* a pushed success notification without action (no CTA) replaces the notification in the state.
* a pushed notification with an action (CTA) doesn't replace the existing notification in the state.
* added and removed notification from the state are based on pushed and existing notification type.

#### A notification center at application level
Creation of a notification domain, which is a list of notifications. Here is the proposal about the notification entity:

```ts
type Notification = {
  id: string
  type:  'success' | 'error' | 'warning' | 'info'
  title: string
  message?: string
  action?: 'refresh'
}
```

#### Notifications component
A Notifications component reads and remove notifications from the state. It displays them as `<Toast/>` at application level.

## Additional informations
None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206528807) by [Unito](https://www.unito.io)

**Comment by 0xLodz** [comment]
@ChaimaaZaoui what happens when several snackbar must be displayed at the same time? Imagine we copy some metadata that trigger the "Copy" snackbar, then we click on a button that triggers this warning snackbar. Is the second one appears above the first one? Is this behaviour similar on both desktop and mobile? Thanks

**Comment by ChaimaaZaoui** [comment]
@0xLodz for the toasts that such "Copy" they should be displayed despite the error snack bar since those are informative to the user and end up disappearing without any action from the user.
Keep in mind that 2+ error could never happen simultaneously its always the first one that the system detects that will be displayed to the user.

**Comment by 0xLodz** [comment]
@ChaimaaZaoui 
The product team doesn't have an easy way to test notifications with CTA button because app must be connected to the ontology. Here is a short video showing the component behaviour:
https://www.awesomescreenshot.com/video/17235852?key=bcbbbb6568ad69d643bd75e4d5fbcbac

The toast's display is triggered from the copy button only for this demo.

Behaviour reminder from the spec:
The user must either to press the `escape` key or, as shown in the video, click outside of the toast in order to hide it.

**Comment by ChaimaaZaoui** [comment]
According to the video and the behaviour of error snackbars, all scenarios have passed.
