### ISSUE TITLE
Error form - general problem

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#176]
# Feature: Server problem

> **As an** end user on the error page of server problem ,
> **I want** to be able to fill a form
> **So that** I inform OKP4 about the detail of the encountered problem 

### Scenario I : First page of the error form

**Given that** I am an end user on the error page of server problem,
**When** I click on `Contact us` button
**Then** I should land on the `first page` of the error form
**And** a text is displayed :

> Tell us mode about the error

**And** different fields are displayed below the text :  

Title; description; field type; Required field
- Description ; Insert the detail of the error including steps to reproduce, actual result, expected result.... ; Required ; Text 
- Display ; N/A ; Dropdown menu containing :
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- Used operating system ; N/A ; not required; Dropdown menu containing : 
- [ ] Linux
- [ ] Windows
- [ ] macOS
- [ ] iOS
- [ ] Android
- [ ] Chrome OS
- [ ] Other
- Browser ; N/A ; not required ; Dropdown menu containing
- [ ] Google Chrome	
- [ ] Safari	
- [ ] Mozilla Firefox	
- [ ] Microsoft Edge	
- [ ] Internet Explorer	
- [ ] Opera
- [ ] Other	
- Was your wallet logged ? ; N/A ; not required; check box
- [ ] Yes
- [ ] No
- Have you refreshed the page ? ; N/A ; not required; check box
- [ ] Yes
- [ ] No

**And** and an `OK ` button

### Scenario II : Second page of the error form
**Given that** I am an end user on the first page of the error form,
**And** I have filed the required fields
**When** I click on `Ok` button
**Then** I should land on the `Keep in touch` page similar to the one on "Give us feedback" form

### Scenario III : Submiting the form
**Given that** I am an end user on the second page of the error form,
**When** I click on `Submit` button
**Then** an email notification should be sent to : 

- [ ] m.dechamp-guillaume@okp4.com
- [ ] c.zaoui@okp4.com

### Mockups
N/A

### Environment

- staging URL: <https://app.staging.okp4.network/>

## Additional informations

N/A

**Comment by YoanOKP4** [comment]
It's done ! ✔️
https://okp4.typeform.com/to/GkWxots6
FYI @ManonPoint26

**Comment by ChaimaaZaoui** [comment]
Hi @YoanOKP4, @ManonPoint26 
There are two things I'd like to correct on the form please :

1. Chance the tab name from "GIVE US FEEDBACK" to "ERROR FORM"
![image](https://user-images.githubusercontent.com/129745194/231453153-f7deed38-073c-40a4-bec3-10a1d0fe7598.png)

2. First question, correct the spelling "mode" => "more" 
![image](https://user-images.githubusercontent.com/129745194/231453494-7881b626-3104-4a4f-b945-89c6c30d04ff.png)

**Comment by YoanOKP4** [comment]
Done
