### ISSUE TITLE
Chore: Remove console logs in production environment

### ISSUE THREAD

**Issue by 0xLodz** [okp4/dataverse-portal#179]
# Chore: Remove console logs in production environment

> **As a** developer,
> **I want** to see console logs only non-production environments
> **So that** no console logs appear in the production environment

### Scenario

**Given that** I am a user of the Dataverse Portal,
**And** I am using a *desktop* device,
**When** I open the browser developer tools in production
**Then** I don't see any console.log from the application.
**And** I only see console.log from the application in non-production environments

## Requirements

1. Add a Vite plugin or any similar solution that help us to deal with console logs without adding conditions in the code based on the env.

## Resources

- [discussion about the requirement](https://github.com/okp4/dataverse-portal/pull/175#discussion_r1165290775)

- [Vite plugin](https://www.npmjs.com/package/vite-plugin-remove-console)

- staging URL: <https://app.staging.okp4.network/>

## Additional informations

None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206528851) by [Unito](https://www.unito.io)

**Comment by ChaimaaZaoui** [comment]
I can't regenerate the case with my accounts, @0xLodz tested and it's all ok
