### ISSUE TITLE
[Wallet] Wallet connexion - Desktop behaviour

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#183]
# Feature: [Wallet] Wallet connexion - Desktop behaviour

> **As an** end-user navigating the portal on a desktop
> **I want** to connect my wallet
> **So that** I have access to my know balance in order to accomplish transactions on the portal

### Scenario 1: Log in - Keplr launch

**Given that** I am an end-user navigating the portal (on desktop)
**When** I click on `Connect my wallet` on top of the wallet menu
**Then** Keplr extension is launched on a pop-up page

### Scenario 2 : Log in - Wallet connected (on desktop)
**Given that** I am an end-user
**And** Keplr extension has launched
**When** my Keplr account is connected
**Then** a short cut of my OKP4 public key is to be displayed on top of the wallet menu

### Scenario 3 : Wallet menu (on desktop)
**Given that** I am an end-user
**And** my Keplr account is connected
**When** I click on the public key
**Then** the wallet menu is dropped down
**And** the menu has 

- KNOW balance
- `Log out` Button

### Scenario 4 : Log out button 
**Given that** I am an end-user with a connected wallet
**And** the wallet menu is dropped down
**When** I click on the `Log out` button
**Then** my kepler wallet is to be logged out
**And** the menu takes its initial state of `Connect my wallet`

### Scenario 5 : Install Keplr (Extension not supported in the browser)
**Given that** I am an end-user navigating the portal
**When** I click on `Connect my wallet` on top of the wallet menu
**And** Keplr extension is not installed on my browser
**Then** a snack-bar suggesting to install the app is displayed with the following content :
> Sorry, you don't have the extension 
> You must have the Keplr extension in order to be able to connect your wallet.
- `Keplrlogo Install Keplr` button

Mock-up 3

**When** I click on the `Install Keplr` button 
*Then** I am redirected to https://www.keplr.app/download

### Scenario 5 : Internationalisation 
ENG:
> Sorry, you don't have the extension 
> You must have the Keplr extension in order to be able to connect your wallet.
- Install Keplr
- Connect my wallet
- KNOW
- Log out

FR
> Désolé, vous n'avez pas l'extension 
> Vous devez disposer de l'extension Keplr pour pouvoir connecter votre portefeuille.
- Installer Keplr
- Connecter mon portefeuille
- KNOW
- Se déconnecter

DE
> Sie haben die Erweiterung leider nicht. 
> Sie müssen die Keplr-Erweiterung haben, um Ihre Brieftasche anschließen zu können.
- Keplr installieren
- Meine Brieftasche verbinden
- KNOW
- Abmelden

### Mockups
mock-up 1
![image](https://user-images.githubusercontent.com/129745194/233952329-736ae53c-08dc-43d2-91ae-e17b03bb19de.png)

mock-up 2
![image](https://user-images.githubusercontent.com/129745194/233952499-a41983e8-8696-4ee9-a58b-0efff2ffca98.png)

mock-up 3
![image](https://user-images.githubusercontent.com/129745194/234330042-e6531990-e3ff-4965-8e87-d67b4f0cb431.png)

### Environment

- staging URL: <https://app.staging.okp4.network/>

## Additional informations

None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206528875) by [Unito](https://www.unito.io)

**Comment by ChaimaaZaoui** [comment]
DOR
- [ ] title, description, and value statement
- [ ] acceptance criteria (scenarios)
- [ ] mockups (all devices and themes)
- [ ] labels added
- [ ] US presented to DEV team (refinement)
- [ ] attached to an epic
- [ ] estimation (planning poker)
- [ ] external dependencies if applicable

**Comment by ChaimaaZaoui** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-board--63e210cc9b1f2f73ee3f4e5f/issues/okp4/dataverse-portal/183?planning-poker) with Zenhub @0xLodz @AnjaMis @ErikssonJoakim @lolottetheclash

**Comment by ChaimaaZaoui** [comment]
Additional information:
To close the dropdown wallet menu, the user clicks outside the menu or uses `esc`

**Comment by ChaimaaZaoui** [comment]
@ccamel I don't know if it's accurate to says that we display the public key. isn't it just the address that needs to be displayed ?
when we talk a public key do I need to add the precision of what `multibaseValue` (Hexadecimal, decimal, base58) it uses ?

**Comment by ccamel** [comment]
@ChaimaaZaoui these are different things. First of all, we must distinguish between the wallet as a login device, and the wallet as a payment device. As a consequence, if in the context of the use case, it's the login that is important, it would be appropriate to display `DIDs` (which can be, but it depends on the cases, a representation of the public key). If it's payment that is highlighted, the address of the connected wallet should be displayed instead.

We have to think about, but if we consider a wallet-based authentication first, my preference would be a mix of the 2, because in the context of the portal, the identity is necessary. Also, in the button it would be appropriate to display the `DID`, and below, the addresses of the wallets connected with their associated balances. Some design thinking would be welcome.

**Comment by ChaimaaZaoui** [comment]
### Connection error

When the user whishes to establish a connexion with a wallet (keplr for instance), they could encounter two types of errors 

- [ ] rejecting the request connection
- Click on connect my wallet
- Requesting connection pop-up launched
 ![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/68b9a749-6e24-4372-9c95-e6dd588ccd3d)
- Click on `Reject` **or** closes the pop-up
- User receives rejection error with the following text: 
ENG
> Wallet connection failed
> Wallet connection request has been rejected

FR
> La connexion au portefeuille a échoué
> La demande de connexion au portefeuille a été rejetée

DE
> Wallet-Verbindung fehlgeschlagen
> Die Anfrage zur Verbindung mit der Wallet wurde abgelehnt.

![image](https://github.com/okp4/dataverse-portal/assets/129745194/522280e0-565d-42ab-a373-3c9cfcc51f9b)

**Comment by ChaimaaZaoui** [comment]
- [ ] The system couldn't connect to the blockchain or encountering other network issues
- The user receives an error with the following text

ENG
> Wallet connection error
> Due to network issues, we failed to connect your wallet. Please try again later.

FR
> Erreur de connexion au portefeuille
> En raison de problèmes de réseau, nous n'avons pas réussi à connecter votre portefeuille. Veuillez réessayer plus tard.

DE
> Fehler bei der Verbindung zur Brieftasche
> Aufgrund von Netzwerkproblemen konnten wir Ihre Brieftasche nicht verbinden. Bitte versuchen Sie es später noch einmal.

![image](https://github.com/okp4/dataverse-portal/assets/129745194/ac74478d-a262-4bfc-abf3-3dc811b261cc)

**Comment by ChaimaaZaoui** [comment]
Note that these errors are closed when the user clicks `esc` on desktop or outside the snackbar on all devices

**Comment by ChaimaaZaoui** [comment]
Tested => success
