### ISSUE TITLE
[Error] - General problem 

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#190]
# Feature: Route problem
> **As an** end user navigating the portal ,
> **I want** to be informed if a page is encountering an error (other than server/route)
> **So that** I can react accordingly to solve the problem

### Scenario I : default display (desktop / Tablet) 
**Given that** I am an end user navigating the web portal,
**When** I click on a button or link 
**And** there is an error other than 404 / 500
**Then** I should land on the error page dedicated to the "General problem"
**And** a text is displayed on the screen : 
> Sorry,
> An error has occurred processing your request.
> We now know about this problem and we are working to fix it. In the mean time here is what you can do :

_Please copy this text (there is a typo error on mock-ups)_

**And** 2 buttons are available side to side : 

* `Go to the home page`  - `Contact us`

### Scenario II : Mobile display
**Given that** I am an end user navigating the web portal,
**When** I click on a button or link 
**And** there is an error other than 404 / 500
**Then** I should land on the error page dedicated to the "General problem"
**And** a text is displayed on the screen : 
> Sorry,
> An error occurred processing your request.
> We now know about this problem and we are working to fix it. In the mean time here is what you can do :

**And** 2 buttons are available one below the other : 

* `Go to the home page`  - `Contact us`

### Scenario III : Contact us button
**Given that** I am an end user on the of the route problem error page,
**When** I click on `Contact us` button
**Then** I should be redirected to error form :    https://okp4.typeform.com/to/GkWxots6

### Scenario IV : Go to the home page button
**Given that** I am an end user on the of the general error page,
**When** I click on `Go to the homepage`  button
**Then** I should be redirected to the portal homepage

### Scenario V: Internalization
Following the selected language, the content on the page is to be displayed accordingly : 

**ENG**

> Sorry,
> An error has occurred processing your request.
> We now know about this problem and we are working to fix it. In the mean time here is what you can do :
> `Go to the home page`
>`Contact us`

**FR**
> Désolé,
> Une erreur s'est produite lors du traitement de votre demande.
> Nous sommes maintenant informés de ce problème et nous nous efforçons de le résoudre. En attendant, voici ce que vous pouvez faire :
>- `Retourner à l'accueil`
>- `Nous contacter`

**DE**
> Entschuldigung,
> Bei der Bearbeitung Ihrer Anfrage ist ein Fehler aufgetreten.
> Wir wissen jetzt von diesem Problem und arbeiten daran, es zu beheben. In der Zwischenzeit können Sie folgendes tun:
>- `Zur Homepage gehen`
>- `Kontakt`

### Mockups

* **Desktop Dark :**

![image](https://user-images.githubusercontent.com/129745194/233612310-65ee7bce-4823-4510-abe5-18f93a7b2e75.png)

* **Desktop Light**
![image](https://user-images.githubusercontent.com/129745194/233612361-bb372425-7038-4358-8ae4-efd259640e7a.png)
* *_Tablet Dark / Light *_
![image](https://user-images.githubusercontent.com/129745194/233612415-5fbbcc48-9519-4dfa-8078-92489247f78e.png)
* **Mobile Dark / Light**
![image](https://user-images.githubusercontent.com/129745194/233612536-e2e132b2-4c20-4335-ae3a-2fcefc02ed4e.png)

### Environment

* staging URL: <https://app.staging.okp4.network/>

## Additional informations
None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206528961) by [Unito](https://www.unito.io)

**Comment by ChaimaaZaoui** [comment]
- [ ] DOR
- [ ] ESTIMATION

**Comment by MdechampG** [comment]
@AnjaMis How can I test it ?

**Comment by AnjaMis** [comment]
@MdechampG unfortunately there is no way you can test this, this error page appears when there is a mistake in our code. We would need to create an error on purpose and push it to staging for you to test it, but that doesn't sound like a good idea...

**Comment by MdechampG** [comment]
Ok so should we validate this issue anyway ? @lolottetheclash @ccamel

**Comment by lolottetheclash** [comment]
> Ok so should we validate this issue anyway ? @lolottetheclash @ccamel

It was tested locally and working well so I think we can validate it.
