### ISSUE TITLE
[Dataverse] Additional filters - Default & multiselect search

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#196]
# Feature: [Dataverse] Additional filters
> **As an** end-user of the portal on the `.../dataverse `page,
> **I want** to filter the dataverse 
> **So that** only items having the metadata I need are shown

### Scenario 1 : Default display (Desktop, mobile, tablet)
**Given that** I am an end-user navigating the portal
**And** I am using a _desktop_ device,
**When** I am on `.../dataverse `page,
**Then** filters should be displayed in the following order

* Data spaces
* Topics
* Service categories
* Data geographical coverage
* Data temporal coverage
* Data format
* Data license
**And** by default all the filters are open
**And** no item is selected in any filter

### Scenario 2: Filter type : Multiselect search
**Given that** I am an end-user navigating the portal
**When** I am on `.../dataverse `page,
**Then** filters are shown on the left side of the page on desktop **Or** after clicking see filters on mobile
**And** the fields available are :

* an autocomplete `search bar` at the top of the list, 
* the three first items of the list are shown
* the `scroll bar` of the list is on the right
* the list is ordered following an alphabetical order
* By default no selected item

_the concerned filters are :  Data spaces ; Topics; Service categories ;  Data geographical coverage ; Data format ; Data license_

_i : The Autocomplete option provides suggestions while you type into the field and filter the results automatically_

### Scenario 3 : Internationalisation 
ENG: 

* Data spaces
* Topics
* Service categories
* Data geographical coverage
* Data temporal coverage
* Data format
* Data license
* Search a data space
* Search topics
* Search categories
* Search country, regions ...
* Search format
* Search license
* No results found

FR

* Espaces de données
* Sujets
* Catégories de services
* Couverture géographique des données
* Couverture temporelle des données
* Format des données
* Licence des données
* Aucun résultat trouvé
* Rechercher dans un espace de données
* Rechercher des sujets
* Rechercher des catégories
* Rechercher un pays, des régions ...
* Rechercher un format
* Rechercher une licence

DE

* Datenräume
* Themen
* Dienstkategorien
* Geografische Abdeckung der Daten
* Zeitliche Abdeckung der Daten
* Datenformat
* Lizenz der Daten
* Keine Ergebnisse gefunden

* Suche in einem Datenraum
* Themen suchen
* Kategorien suchen
* Suche nach Land, Registern ...
* Suche nach Format
* Suche nach Lizenz

### Mockups
Mock-ups are available on Figma Dev FIle, Page "Version 2 - FOR LATER"

![image](https://user-images.githubusercontent.com/129745194/234339703-64b1753b-6be8-4b1a-8fe3-cdf67aef4682.png)

### Environment

* staging URL: <https://app.staging.okp4.network/>

## Additional informations
**EDIT** from @0xLodz: filters can be updated, open/closed using the keyboard.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206528990) by [Unito](https://www.unito.io)

**Comment by ChaimaaZaoui** [comment]
DOR
- [ ] title, description, and value statement
- [ ] acceptance criteria (scenarios)
- [ ] mockups (all devices and themes)
- [ ] labels added
- [ ] US presented to DEV team (refinement)
- [ ] attached to an epic
- [ ] estimation (planning poker)
- [ ] external dependencies if applicable

**Comment by ChaimaaZaoui** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-board--63e210cc9b1f2f73ee3f4e5f/issues/okp4/dataverse-portal/196?planning-poker) with Zenhub @lolottetheclash @ErikssonJoakim @AnjaMis @0xLodz

**Comment by 0xLodz** [comment]
@ChaimaaZaoui Do we display a fallback message when the filter search provide no results? Thanks

**Comment by ChaimaaZaoui** [comment]
After today's short demo, here are the key elements left to do :
- When an item in list is too long, it should be displayed maximum in two lines, then an ellipse is to be added if there's further text.
- Don't overlay a dropdown and the list that's already shown
- Set the height of the list to display 3 

Tags will be handled in a second phase

**Comment by 0xLodz** [comment]
@ChaimaaZaoui Do we have translations for placeholders ( "Search country, region...", "Search topics", etc)? Thanks

**Comment by 0xLodz** [comment]
@SpicySalm0n Is the fallback message for the filter search bar available on the Figma? Thanks

**Comment by ChaimaaZaoui** [comment]
Here is the design of the fallback message : 
![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/82c64789-0220-48c0-882c-3745418f617f)

**Comment by MdechampG** [comment]
# Test 20/06

McBook Pro (Firefox) 

-----

Scenario 1 : Default display (Desktop, mobile, tablet) ✅ 
(Except from Data temporal coverage which will be handled in #208)

Scenario 2: Filter type : Multiselect search ✅ 

Scenario 3 : Internationalisation ✅
