### ISSUE TITLE
[Dataverse] Details page - Back to Dataverse 2

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#197]
# Feature: Details page - Back to Dataverse 2
> **As a** user of the portal on the details page of a Dataverse item,
> **I want** to go back to the Dataverse
> **So that** I continue to explore the resources available in the Dataverse

### Scenario: General display
**Given that** I am a user authenticated or not,
**And** I am using a _desktop_ device,
**When** I am on on the details page of any Dataverse item 
**Then** I should see the word `Dataverse` next to the back arrow (see mock up)

### Scenario: Back to Dataverse
**Given that** I am a user authenticated or not on on the details page of any Dataverse item,
**And** I am using a _desktop_ device,
**When** I click on the ` <- Dataverse `
**Then** I am redirected to `/dataverse`
_note mean when I click on the arrow or on the word dataverse both should take me back to the explore page_

### Scenario: Mobile display
**Given that** I am a user authenticated or not,
**And** I am using a _mobile_ device,
**When** I am on on the details page of any Dataverse item 
**Then** I should see `<- Dataverse`

### Scenario: Internationalization
ENG `Dataverse`
FR   `Dataverse`
DE  `Dataverse`

### Mockups
![image.png](https://images.zenhubusercontent.com/616e76157d9dbb44e290ed55/046107a2-1a46-4c75-b9e9-2707cbe1f654)

### Environment

* staging URL: <https://app.staging.okp4.network/>

## Additional informations
None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206529011) by [Unito](https://www.unito.io)

**Comment by ChaimaaZaoui** [comment]
Definition of Ready

- [ ] title, description, and value statement
- [ ] acceptance criteria (scenarios)
- [ ] mockups (all devices and themes)
- [ ] labels added
- [ ] US presented to DEV team (refinement)
- [ ] attached to an epic
- [ ] estimation (planning poker)
- [ ] external dependencies if applicable

**Comment by AnjaMis** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-board--63e210cc9b1f2f73ee3f4e5f/issues/okp4/dataverse-portal/197?planning-poker) with Zenhub @lolottetheclash @ErikssonJoakim @0xLodz @fredericvilcot @amimart @bdeneux @d3ployment @DValide @jeremylgn @JoeyDjr @MdechampG @NourKired @SonnevilleDamien

**Comment by AnjaMis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-board--63e210cc9b1f2f73ee3f4e5f/issues/okp4/dataverse-portal/197?planning-poker) with Zenhub @ccamel

**Comment by ChaimaaZaoui** [comment]
Test executed on Firefox => **Passed**
