### ISSUE TITLE
[Governance] Mobile behaviour

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#200]
# Feature [Governance] – Browsing governance on mobile or tablet
> **As a** an end-user,
> **I want** to explore the governance of a Data space on a mobile / tablet 
> **So that** I read the terms and conditions of its section, subsections, articles and paragraphs

### Scenario 1: Default display (Mobile & Tablet)
**Given that** I am a user of the web portal (unauthenticated or authenticated) 
**And** I'm on a Data Space governance page after clicking on `Access governance` on data space page,
**Then** I should land on the first section and first subsection available
**And** the field has 

* Drop-down menu with title of the section and down chevron
* Text area with section title 
* Text area with description of the section (only if available)
* Text area with sub-section title
* Text area with description of the sub-section (only if available)
* A container 
-- Text area with article title
-- Text area with article description
* Paragraph card (if available)
-- Paragraph icon
-- Paragraph title
-- Paragraph description

_Note that every section has at least a sub-section with at least an article (paragraph is not mandatory, if paragraph available then automatically it has a description)_
see mockup 1 (with and without descriptions)

### Scenario 2 : Container behaviour - subsection w/ 1 article
**Given that** I am a user on a data space governance page 
**When** I select a section with the selected subsection having only one article
**Then** the container is by default open
**And** the container has the article title on top
**And** the container has the description of the article as a subtitle (only if available)
**and** a card representing each paragraph
see mock-up 1

### Scenario 3 : Container behaviour - subsection w/ 2+ articles
**Given that** I am a user on a data space governance page 
**When** I select a section with the selected subsection having 2 or more articles
**Then** the first container of the first article is by default open
**And** the other containers of the following articles are closed
See mock-up 2

### Scenario 4 : Container Open - subsection w/ 2+ articles
**Given that** I am a user on a data space governance page 
**When** I select a section with the selected subsection having 2 or more articles
**Then** the open container displays 

* On the left : the title of the article and as a subtitle the description of the article if available
* On the right : 
* a square with the number of paragraphs in the article (starting from 1)
* `chevron up` icon
Mock-up 3

### Scenario 5: Container closed - subsection w/ 2+ articles
**Given that** I am a user on a data space governance page 
**And** I am using a desktop device,
**When** I select a section with the selected subsection having 2 or more articles
**Then** the closed container displays 

* On the left : the title of the article
* On the right : 
* a square with the number of paragraphs in the article (starting from 1)
* `chevron down` icon

### Scenario 6: opening & closing a container
**Given that** I am a user on a data space governance page 
**And** I select a section with the a subsection having 2 or more articles
**When** I click on the top part of the container
_the click must be available on the whole top part (title, empty area, number, chevron)_
**Then**  it closes if it's open (or opens if it's closed)

### Scenario 7: Paragraph card 
**Given that** I am a user on a data space governance page 
**And** I am using a desktop device,
**When** I select a section with a selected subsection 
**And** the container of one of its articles is open 
**Then** each paragraph is displayed on a card in the following order

* icon
* Paragraph title
* Paragraph description (displayed max in 4 rows)
* `See more` button _(displayed if 5 or more rows are available in the description)_
_For now the see more button is disabled because its behaviour is TBD_

Mock-up 4

### Scenario 8: Paragraph card - Description with DID
**Given that** I am a user on a data space governance page 
**And** I am using a desktop device,
**When** I select a section with a selected subsection 
**And** the container of one of its articles is open 
**And** a paragraph contains DIDs
**Then** each DID is displayed on a separate row with

* `...` in the middle for the short cut
* `Copy` icon button 
_i - the copy function will be in V2_
Mock-up 4

### Scenario 9 : Section drop-down menu behaviour (Mobile & Tablet)
**Given that** I am a user of the web portal (unauthenticated or authenticated) 
**And** I'm on a Data Space governance page
**And** I click on the drop down menu
_(click must be available on the whole the component not only the text or the chevron)_
**Then** the displayed menu contains :

* titles of section available in this data space 
* The title must be kept in one line, if it's too long then an ellipse is added at the end 
* right arrow on the right of sections with two or more subsections
* no right arrow for sections with only one subsection

**When** I select a section with multiple subsection
**then** a second page of the drop-down menu is displayed and it contains : 

* `<- Back` button allowing to go back to the first page of the menu
* titles of the subsections of the selected section
* The title must be kept in one line, if it's too long then an ellipse is added at the end 
mock-up 5

### Scenario 10 : Change section to a section with one subsection (Mobile & Tablet)
**Given that** I am a user of the web portal (unauthenticated or authenticated) 
**And** I'm on a Data Space governance page
**And** I click on the drop down menu
**And** I select a section with no subsection (no right arrow)
**Then** the drop-down menu closes 
**And** the title of section is now visible on the drop-down menu
**And** I land on the section description following the default display
mock-up 5

### Scenario 11 : Change section to a section with  multiple subsection (Mobile & Tablet)
**Given that** I am a user of the web portal (unauthenticated or authenticated) 
**And** I'm on a Data Space governance page
**And** I click on the drop down menu
**And** I select a section with subsections (right arrow)
**And** I am redirected to the second page of the menu
**And** I select a subsection 
**Then** the drop-down menu closes 
**And** the title of section is now visible on the drop-down menu 
_Note that it's not the title of the subsection that is displayed on the of the drop-down menu_
**And** I land on the section description following the default display
mock-up 5

### Scenario 12 : Scrolling sections / subsection 
**Given that** I am a user of the web portal (unauthenticated or authenticated) 
**And** I'm on a Data Space governance page
**And** I click on the drop down menu 
**And** the list of sections or subsections is too long to show all
**Then** I should be able to scroll down and up the menu
_No scroll bar is available, it's only visual as the last section or subsection is cropped showing the user that they can scroll_
mock-up 5

### Scenario 13 : Internalisation
ENG
See more
Back

FR
Voir plus
Retour

DE
Mehr sehen
Zurück

### Mockups
Mockup 1
![image](https://user-images.githubusercontent.com/129745194/234285246-1c0619e8-8ff3-411b-b62e-2f9e41609b66.png)

mockup 2
![image](https://user-images.githubusercontent.com/129745194/234295856-e2a0b5d5-8659-4bb3-ac74-336538e56f0c.png)![image](https://user-images.githubusercontent.com/129745194/234295961-eedda67c-f87a-4ebc-b807-cb0587c411ba.png)

mock up 3 
![image](https://user-images.githubusercontent.com/129745194/234298672-5ff74faa-52f0-446e-ab64-bae573545fcc.png)

mock-up 4
![image](https://user-images.githubusercontent.com/129745194/234302576-6cd739d4-b1cf-414d-9998-b9d7bb02927b.png)

mock-up 5
![image](https://user-images.githubusercontent.com/129745194/234303858-8560db55-55c4-4cb5-96e6-4585fee4aee4.png)

mock-up - 6
Light mode 
![image](https://user-images.githubusercontent.com/129745194/234334652-49935b39-53bd-4156-918d-a6d7ef96fcb8.png)

### Environment

* staging URL: <https://app.staging.okp4.network/>

## Additional informations
None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206529032) by [Unito](https://www.unito.io)

**Comment by ChaimaaZaoui** [comment]
**Definition of Ready**

- [ ] title, description, and value statement
- [ ] acceptance criteria (scenarios)
- [ ] mockups (all devices and themes)
- [ ] labels added
- [ ] US presented to DEV team (refinement)
- [ ] attached to an epic
- [ ] estimation (planning poker)
- [ ] external dependencies if applicable

**Comment by ChaimaaZaoui** [comment]
To go from one page to another in this dropdown menu, the first page slides from the right to the left
I'll provide an animation
Note that this is explained in design system for all cascade menus

**Comment by ChaimaaZaoui** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-board--63e210cc9b1f2f73ee3f4e5f/issues/okp4/dataverse-portal/200?planning-poker) with Zenhub @lolottetheclash @ErikssonJoakim @0xLodz @AnjaMis

**Comment by ChaimaaZaoui** [comment]
Regarding the animation for sliding the menu pages, lisa couldn't design it, however here is a link to a video showing design idea
https://www.google.com/search?q=animation+dropdown+cascade&oq=animation+dropdown+cascade&aqs=chrome..69i57j33i160l4.4968j0j7&sourceid=chrome&ie=UTF-8#fpstate=ive&vld=cid:6858b6d1,vid:IF6k0uZuypA

**Comment by 0xLodz** [comment]
@SpicySalm0n when an article has a description, do we want to display the number of paragraph and the chevron at the title level, or as it is displayed in this screenshot (which represents the current state of the [feature implementation](https://github.com/okp4/dataverse-portal/pull/222))? cc @ErikssonJoakim 
<img width="493" alt="image" src="https://github.com/okp4/dataverse-portal/assets/8344874/1f629f0c-9567-4a8d-a511-38d9386122ad">

**Comment by SpicySalm0n** [comment]
@0xLodz they should be aligned to the title!

**Comment by MdechampG** [comment]
# test 12/06

Scenario 1: Default display (Mobile & Tablet) ✅ 

Scenario 2 : Container behaviour - subsection w/ 1 article ✅ 

Scenario 3 : Container behaviour - subsection w/ 2 or more articles ❓ -> Not the case in the Rhizome governance.
Scenario 4 : Container Open - subsection w/ 2+ articles ❓ -> Not the case in the Rhizome governance.
Scenario 5: Container closed - subsection w/ 2+ articles ❓ -> Not the case in the Rhizome governance.
Scenario 6: opening & closing a container ❓ -> Not the case in the Rhizome governance.

Scenario 7: Paragraph card ✅ 

Scenario 8: Paragraph card - Description with DID => will be in V2

Scenario 9 : Section drop-down menu behaviour (Mobile & Tablet) ✅ 

Scenario 10 : Change section to a section with one subsection (Mobile & Tablet) ✅ 

Scenario 11 : Change section to a section with multiple subsection (Mobile & Tablet) ✅ 

Scenario 12 : Scrolling sections / subsection ✅ 

Scenario 13 : Internalisation ✅ 

@ErikssonJoakim how can I test the scenarii 3, 4, 5 and 6 ?

**Comment by MdechampG** [comment]
# test 13/06

Scenario 3 : Container behaviour - subsection w/ 2 or more articles ✅ 

Scenario 4 : Container Open - subsection w/ 2+ articles ✅ 

Scenario 5: Container closed - subsection w/ 2+ articles ✅ 

Scenario 6: opening & closing a container ✅
