### ISSUE TITLE
[Portal] Field copy in CORE Metadata and Audit Metadata

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#219]
# Feature: [Portal] Field copy in CORE Metadata and Audit Metadata

> **As a** an end user,
> **I want** to copy a DID in my dashboard 
> **So that** I can use it elsewhere 

### Scenario: Copy DID

**Given that** I am an end user,
**And** I am using a *desktop* or a *mobile* device,
**When** a `copy `icon button is available next to the DID in the UI
**And** I click on the `copy `icon
**Then** the `copy `icon is animated to validate the copy
**And** the concerned DID is copied in my clipboard
**And** the icon goes back to its initial state after 2 seconds 

_Note that the copy snackbar is not required any more_ 

this is applicable now in
- detail page of any dataverse resource 
- governance paragraph 

### Scenario: Failed Copy DID

**Given that** I am an end user,
**And** I am using a *desktop* or a *mobile* device,
**When** a `copy `icon button is available next to the DID in the UI
**And** I click on the `copy `icon
**Then** the `copy `icon is animated to a cross icon to show that the copy is failed 
**And** the icon goes back to its initial state after 2 seconds 

### Mockups

https://user-images.githubusercontent.com/129745194/235853067-3a44c8c8-fc4b-4ad4-ba66-0857fabbfc3e.mov

![image](https://user-images.githubusercontent.com/129745194/236149438-6e1a32b6-10a0-4882-8156-0f6ad9da2edc.png)

### Environment

- staging URL: <https://app.staging.okp4.network/>

## Additional informations

None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206529480) by [Unito](https://www.unito.io)

**Comment by ChaimaaZaoui** [comment]
**Definition of Ready**

- [ ] 
- [ ] - title, description, and value statement
- [ ] - acceptance criteria (scenarios)
- [ ] - mockups (all devices and themes)
- [ ] - labels added
- [ ] - US presented to DEV team (refinement)
- [ ] - attached to an epic
- [ ] - estimation (planning poker)
- [ ] - external dependencies if applicable

**Comment by ChaimaaZaoui** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-board--63e210cc9b1f2f73ee3f4e5f/issues/okp4/dataverse-portal/219?planning-poker) with Zenhub @0xLodz @AnjaMis @ErikssonJoakim @fredericvilcot @lolottetheclash

**Comment by ChaimaaZaoui** [comment]
Technical requirement :
- The DID needs to be detected to allow the copy

**Comment by lolottetheclash** [comment]
@ccamel could you send us some `did` examples?

**Comment by ccamel** [comment]
@lolottetheclash sure.


Content | Expected DIDs
-- | --
`"Here's a DID: did:key:z6MkhaXgBZDvotDkL5257faiztiGiC2QtKLGpbnnEGta2doK and another one: did:ethr:0xb9c5714089478a327f09197987f16f9e5d936e8a."` | [`did:key:z6MkhaXgBZDvotDkL5257faiztiGiC2QtKLGpbnnEGta2doK`, `did:ethr:0xb9c5714089478a327f09197987f16f9e5d936e8a`]
``"We can denote DID as code using backticks like in `did:key:z6MkhaXgBZDvotDkL5257faiztiGiC2QtKLGpbnnEGta2doK`"`` | [`did:key:z6MkhaXgBZDvotDkL5257faiztiGiC2QtKLGpbnnEGta2doK`]
`"As DIDs are URI, they are percent encoded like in did:method:an%20identifier%20with%20spaces."` | [`did:method:an%20identifier%20with%20spaces`]
`"Some terms looks like DIDs but are not, like did:key, did::1234, dod:key:45, did:key#z6MkhaXgB"` | []

(see https://www.w3.org/TR/did-core/#did-syntax).

**Comment by ChaimaaZaoui** [comment]
Does not concern the governance page.

**Comment by balteo** [comment]
Return to initial state after **2 seconds**.

**Comment by balteo** [comment]
@ChaimaaZaoui Do we keep the copy snackbar for the copy failure scenario?

**Comment by ChaimaaZaoui** [comment]
@balteo no the aim is to no have the snackbar anymore, that's why i mentioned : _Note that the copy snackbar is not required any more_

**Comment by ChaimaaZaoui** [comment]
Tested on Mobile, iOS, Safari => OK
Tested on Desktop, Windows, Firefox => OK
