### ISSUE TITLE
[Share data] Select a storage service - `A local folder` general display

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#235]
> **As a** end-user with an authenticated wallet or not,
> **I want** to reference a dataset in the dataverse,
> **So that** my dataset could be used to create knowledge. 

### Scenario 1: "Select a storage service" general display
**Given that** I am an end user,
**And** I am using a _desktop_ device,
**When** I am in the step "Select a storage service"
**Then** the page is displayed as follows

* **Text**  I SHARE A DATASET
* **Figure** Stepper 
* **Text** Select a storage service
* **Text** MY DATASET IS IN
* **Tab** section 
-- A local folder _(Active tab)_
-- An external storage _(Inactive tab)_

### Scenario 2: `A local folder` general display
**Given that** I am an end user,
**And** I am using a _desktop_ device,
**When** I am in the step "Select a storage service"
**And** I selected the `A local folder` tab
**Then** the tab content is displayed as follows

* **Search bar** Search a storage service
* Service Card
* **Button**`next step >`
* A scroll bar with an infinite scroll and a loader

### Scenario 3: `A local folder` Service card display
**Given that** I am an end user,
**And** I am using a _desktop_ device,
**When** I am in the step "Select a storage service"
**And** I selected the `A local folder` tab
**Then** the service card contains 

* **Text** Service
* **Text** Service title
* **Text**_Publisher : Service publisher_
* **Button**`Select`

### Scenario 4: Default display
**Given that** I am an end user,
**And** I am using a _desktop_ device,
**When** I am in the step "Select a storage service"
**And**`A local folder` tab is selected
**Then** by default

* No service is selected
* `Next step >` is disabled

### Scenario 5: Internationalisation
ENG
> I Share a dataset
> Select a storage service
> My dataset is in
> A local folder
> An external storage
> Search a storage service
> Service 
> Publisher
> Select // Selected
> Next step

FR
> Je partage un jeu de données
> Sélectionner un service de stockage
> Mon jeu de données se trouve dans
> Un dossier local
> Un stockage externe
> Rechercher un service de stockage
> Service 
> Éditeur 
> Sélectionner // Sélectionné
> Prochaine étape

DE
> Ich gebe einen Datensatz frei
> Wählen Sie einen Speicherdienst
> Mein Datensatz befindet sich in
> Einem lokalen Ordner
> Ein externer Speicher
> Suche nach einem Speicherdienst
> Dienst 
> Verleger
> Auswählen // Ausgewählt
> Nächster Schritt

#### Desktop
![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/96f1c6c1-00a0-4f78-ba8b-3f548e756f6a)

### Environment

* staging URL: <https://app.staging.okp4.network/>

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206527439) by [Unito](https://www.unito.io)

**Comment by ChaimaaZaoui** [comment]
DOR
- [x] title, description, and value statement
- [x] acceptance criteria (scenarios)
- [x] mockups (all devices and themes)
- [x] labels added
- [x] US presented to DEV team (refinement)
- [x] attached to an epic
- [x] estimation (planning poker)
- [x] external dependencies if applicable

**Comment by ChaimaaZaoui** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-board--63e210cc9b1f2f73ee3f4e5f/issues/okp4/dataverse-portal/235?planning-poker) with Zenhub @0xLodz @amimart @AnjaMis @ccamel @ErikssonJoakim @fredericvilcot @lolottetheclash

**Comment by lolottetheclash** [comment]
**Tech Spec**

UI - medium & large screen only:

While waiting for the stepper, we can already start developing the entire view, which will then be injected into the stepper.

A non-generic tab component (not really reusable as a classic tab component)
The existing searchable bar (without the "no results" display)
All services as Cards with infinite scroll

**Comment by MdechampG** [comment]
Test 12/06

Scenario 1: "Select a storage service" general display ✔️ 
OK except from the stepper which will be handled in #236 

Scenario 2: A local folder general display 🟠 

- Search bar Search a storage service ✔️ OK (not functional) 
- Service Card ✅ 
- Button next step > :x:
- A scroll bar with an infinite scroll and a loader 🟠  OK but there are 2 scroll bars so it's not easy to navigate

Scenario 3: A local folder Service card display ✅ 

Scenario 4: Default display ✅ 

Scenario 5: Internationalisation :x: 

It's not the same translation for this one : 
<img width="336" alt="image" src="https://github.com/okp4/dataverse-portal/assets/92780073/a4c4a909-f7f3-416a-b13d-e97ba144e74b">

**Comment by MdechampG** [comment]
Test 13/06

Scenario 1: "Select a storage service" general display ✔️
OK except from the stepper which will be handled in https://github.com/okp4/dataverse-portal/issues/236

Scenario 2: A local folder general display ✅

    Search bar Search a storage service ✔️ OK (not functional)
    Service Card ✅
    Button next step > Will be handled in https://github.com/okp4/dataverse-portal/issues/236
    A scroll bar with an infinite scroll and a loader ✔️  (Loader not tested because not enough storages in the catalogue)

Scenario 3: A local folder Service card display ✅

Scenario 4: Default display ✅

Scenario 5: Internationalisation ✅
