### ISSUE TITLE
[Resource referencing] Multi-Step Form with Stepper - V1

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#236]
As a user, 
I want to have a clear understanding of my progress in a multi-step form by visualizing it through a stepper component, 
and I want to be able to navigate through the form using Next and Previous buttons.

### Scenario 1: Navigating a Multi-Step Form with Stepper and Navigation Buttons

Given that I am accessing a Resource referencing process, 
When I start filling out the fields, 
Then I should see a stepper component that visually represents the steps of the process
and indicates the current step I am on.

### Scenario 2: Moving forward
Given that I am on a specific step of the Resource referencing process, 
When I have completed the required fields on the current step, 
Then the `Next `button should be active which allows me to proceed to the next step.

Given that I am on a specific step of the Resource referencing process, 
When I have not completed the required fields on the current step, 
Then the `Next `button remain inactive and non-clickable.

Given that I am on the last step of the Resource referencing process, 
Then the `Next `button should be hidden.

### Scenario 3: Moving backward
Given that I am on a step other than the first step of the Resource referencing process, 
When I want to review or modify the information I provided on the previous step, 
Then I should see a "Previous" button, which allows me to navigate back to the previous step. 

When I click the `Previous` button, 
Then I should be taken back to the previous step, 
and my previously entered information should be preserved.

Given that I am on the first step of the Resource referencing process, 
When I am reviewing or modifying the information provided on the first step, 
Then the "Previous" button should be hidden, as there is no previous step to navigate back to.

### Scenario 4: Internationalisation

Eng
previous
next"

Fr
précédent
suivant

DE
zurück
weiter

#### Desktop

![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/71dfb917-3c54-4c46-b03f-46170171fb7c)

![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/e2f65159-90bc-432f-9e60-fbc6512f0540)

![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/fd956171-c628-4783-81bb-ef4b3a1cd175)

### Environment

- staging URL: <https://app.staging.okp4.network/>

## Additional informations

None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206527369) by [Unito](https://www.unito.io)

**Comment by ChaimaaZaoui** [comment]
Add the navigation part, with the next and previous button

**Comment by ChaimaaZaoui** [comment]
In the error management, do you think it's important to have a refresh button, or is it sufficient that the user clicks again on next or previous ? would the navigation bug be gone ?

**Comment by 0xLodz** [comment]
What type of error are you thinking of? Form errors mainly occur when uploading files. We shouldn't have any errors when clicking on navigation button, as these are disabled until the required fields are filled in.

**Comment by ChaimaaZaoui** [comment]
I don't know if any errors could be encountered when moving from a page to another even if the mandatory fields are filled. If there won't be any, I can take off the error management scenario. @0xLodz

**Comment by 0xLodz** [comment]
## Comparing form libraries

Here is a comparison of three form libraries: [Formik](https://formik.org/), [React Final Form](https://final-form.org/react), and [React Hook Form](https://www.react-hook-form.com/). The comparison is based on several criteria such as performance, ease of implementation, community usage, and size.

| Criteria | Formik | React Final Form | React Hook Form |
| --- | --- | --- | --- |
| Performance | Good, but may have more re-renders | Very good, minimal re-renders | Excellent, minimizes re-renders |
| Ease of Implementation | Moderate, a bit of boilerplate | High, less boilerplate | High, minimal boilerplate |
| Community Usage | Very high, large community | Moderate, less usage compared to Formik and RHF | High, fastest-growing library |
| Size | Moderate, larger than RFF and RHF | Small, smallest of the three | Small, smaller than Formik |
| Validation Library Compatibility | High, seamless integration with Yup | Moderate, requires additional setup | High, compatible with Zod and Yup |

## Technical specification

### Chosen solution
Based on the comparison above and the requirements of the project, the chosen solution for managing form state in this stepper will be [React Hook Form ](https://www.react-hook-form.com/)(RHF), used in conjunction with Zustand for state management and React Router for navigation between steps.

#### Reasons for picking RHF

- **Performance**: RHF minimizes re-renders, leading to better performance, especially for complex forms with many interactions.
- **Ease of Implementation**: RHF requires minimal boilerplate code, making it simpler and faster to implement.
- **Growing Community**: RHF is the fastest-growing form library, indicating that it's being widely adopted and actively maintained.
- **Size**: RHF is smaller than Formik, making it a better choice for keeping the JavaScript bundle size low.
- **Validation**: RHF is compatible with [Zod](https://zod.dev/) and [Yup](https://www.npmjs.com/package/yup), two powerful validation libraries.

### State management
Zustand is used to share state between different parts of the application or persist state between different routes.
Storing form data in the comes with some [considerations](https://github.com/theodorusclarence/rhf-stepform#upload-form).

### Simplified example of an implementation of the stepper:

```jsx
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as zod from 'zod';
import create from 'zustand';
import { BrowserRouter as Router, Routes, Route, useNavigate } from 'react-router-dom';

// Zustand store
const useStore = create(set => ({
  formState: {},
  setFormState: (state) => set({ formState: state }),
}));

const schema = zod.object({
  name: zod.string(),
  // add other fields as needed
});

const Step1Form = () => {
  const navigate = useNavigate();
  const { formState, setFormState } = useStore();
  const { register, handleSubmit } = useForm({
    defaultValues: formState,
    resolver: zodResolver(schema),
  });

  const onSubmit = (data) => {
    setFormState(data);
    navigate('/step2');
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input {...register('name')} />
      {/* add other fields as needed */}
      <button type="submit">Next</button>
    </form>
  );
};

// similar setup for Step2Form, Step3Form, etc.

// router
  <Router>
    <Routes>
      <Route path="/step1" element={<Step1Form />} />
      {/* add other routes as needed */}
    </Routes>
  </Router>
```

For a more detailed implementation, you can refer to this [repository](https://github.com/theodorusclarence/rhf-stepform) which uses React Hook Form, Zustand, and React Router.

Sources:
- https://blog.logrocket.com/react-hook-form-vs-formik-comparison/
- https://dev.to/sm0ke/react-forms-formik-vs-hook-form-vs-final-form-c1e
- https://github.com/theodorusclarence/rhf-stepform

**Comment by 0xLodz** [comment]
@SpicySalm0n how do we make the transition from one step to the next?

**Comment by SpicySalm0n** [comment]
@0xLodz is it possible to have something like that? 
(it's not smooth on the video, I don't have 100% control over the Figma animations but the border radius has to be the same)
The idea is to have the blue fill from left to right. And for green I think a smooth changing color is enough, what do you think?

https://github.com/okp4/dataverse-portal/assets/115076387/23ab9586-1cfd-470f-b840-18e6ad94bfc5

**Comment by 0xLodz** [comment]
@SpicySalm0n Sorry for misleading you, my question was mostly about the content of the step. In our case, the whole from, does it contains any transition as well?
Thanks for the details and the video about the stepper indicator. This is definitely possible to animate it like the video. I guess if the step is not valid anymore, the animation goes to the other side? Thanks

**Comment by SpicySalm0n** [comment]
only this part will remain fixed as well as the previous/next step banner
<img width="154" alt="Capture d’écran 2023-06-08 à 15 39 27" src="https://github.com/okp4/dataverse-portal/assets/115076387/92300291-1be0-4548-9979-f8b953954e01">

**Comment by ChaimaaZaoui** [comment]
I think the fade, as in the first video, is good, no need to go with a movement down.
Thanks

**Comment by lolottetheclash** [comment]
First, thank you for all this well-written study, it's a great job! 😉
I just have a few reservations about using `children` on the stepper.
I think it would have been more practical to use an array of steps. 
This would have made it possible to use `UUIDs` instead of indexes to create the `id` of each step, which is safer.
I think we can avoid the `none` display for non-active steps, by simply displaying the active step in another way.
Also, using an array of steps would allow each step to have its own `onValidate` method, which would be called when the next step is clicked, thus avoiding the need for a `context`.
Finally, just to add a little improvement to the "generic" side of the stepper, I would have updated by `isStepValid` from the `StepperProgressProps` by `stepStatus` (or something like that), which would be a union of `status`. This would make it possible to add nuances if necessary (validated, in error, disabled, etc.).

**Comment by MdechampG** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-board--63e210cc9b1f2f73ee3f4e5f/issues/okp4/dataverse-portal/236?planning-poker) with Zenhub @0xLodz @amimart @ccamel @ErikssonJoakim @fredericvilcot @lolottetheclash

**Comment by 0xLodz** [comment]
@MdechampG Could you please confirm these following german translation for _Previous_ and _Next_ buttons are correct?
```json
"previous": "Vorherige",
"next": "Nächste",
```

Thanks

**Comment by MdechampG** [comment]
@lmarline you are the best one to confirm :)

**Comment by lmarline** [comment]
@0xLodz @MdechampG 
hey, these terms are adjectives used in other situations (followed by others words for example)
It would be better to write :

> "previous": "zurück"
> "next": "weiter"

**Comment by MdechampG** [comment]
@ChaimaaZaoui could you add the internationalisation in the issue ? 
@0xLodz could you change the german version with `zurück` and `weiter` please ?

**Comment by ChaimaaZaoui** [comment]
Tested
