### ISSUE TITLE
[Share data] Select your data - general display 

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#240]
> **As an** end-user who has selected a storage service in the in the "Select a storage service" page,
> **I want** to be able to select my dataset
> **So that** I can upload it to the storage service

### Scenario 1: general display
**Given that** I am an end user,
**And** I am using a _desktop_ device,
**When** I am in "Select a storage service" page with a selected service
**And** clicked on `Next step >`

**Then** the page is displayed as follows

* **Text**  I SHARE A DATASET
* **Figure** Stepper 
* **Text** Select your Data
* **Text** Select the dataset that you want to upload into the storage service.
* A file selection area with text and a button as follows  :
_Drag and drop your files_
Or
`Browse`
* File list with a scroll bar
* Button `< Previous step` always active
* Button `Next step >`

**When** no file is selected
**Then** the `Next step >` is disabled

### Scenario 2: File list
**Given that** I am an end user,
**And** I am using a _desktop_ device,
**When** I am in "Select your data" page with selected files
**Then** the list displays 

* File icon
* the file title as _FileTitle.Type_
* a `trash` button

**When** I click on the `trash` button
**Then** the file is deleted from the selection

### Scenario 3: Internationalisation
ENG

> Select your Data
> Select the dataset that you want to upload into the storage service.
> Drag and Drop your files
> Or
> Browse
> Previous step
> Next step

FR
> Sélectionnez vos données
> Sélectionnez le jeu de données que vous souhaitez télécharger dans le service de stockage.
> Glissez-déposez vos fichiers
> ou
> Parcourez
> Étape précédente
> Etape suivante

DE
> Wählen Sie Ihre Daten aus
> Wählen Sie den Datensatz aus, den Sie in den Speicherdienst hochladen möchten.
> Laden Sie Ihre Dateien per Drag & Drop.
> Oder
> Durchsuchen
> Vorheriger Schritt
> Nächster Schritt

#### Desktop
![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/cd3235a7-c3ce-4dfb-bced-1b7d5c0c067f)

![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/3389074c-219c-47ca-902e-a08c0c00948d)

### Environment

* staging URL: <https://app.staging.okp4.network/>

## Additional informations
None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206527274) by [Unito](https://www.unito.io)

**Comment by ErikssonJoakim** [comment]
**Tech Spec**

| Use Case | API | description |
| - | - | - |
| User clicks on Browse | [input type="file"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file) | On click the browser opens. With multiple attribute assigned the input field accepts multiple files  |
| file selection | [change event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event), [Zustand updating state](https://docs.pmnd.rs/zustand/guides/updating-state) | When selecting files the onChange event fires allowing us to have a handler that dispatches the event target value to the store |
| Display list of files | [Zustand useStore](https://docs.pmnd.rs/zustand/getting-started/introduction#then-bind-your-components,-and-that's-it!) | The list of files can easily be retrieved from the store |
| Removing a list item | [Zustand updating state](https://docs.pmnd.rs/zustand/guides/updating-state) | When clicking on trash button we can have a handler filter the files selected and set the store to all files selected except the one belonging to the list item. As the store state changes the list will update. |

**Comment by ChaimaaZaoui** [comment]
Techspac for the domain is to be done

**Comment by MdechampG** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-board--63e210cc9b1f2f73ee3f4e5f/issues/okp4/dataverse-portal/240?planning-poker) with Zenhub @0xLodz @amimart @ccamel @ErikssonJoakim @fredericvilcot @lolottetheclash

**Comment by lmarline** [comment]
@ChaimaaZaoui hi can you change the translation in german with these modifications below ? The bold text is the modified text. Thanks

Wählen Sie Ihre Daten **aus**
Wählen Sie den Datensatz **aus**, den Sie in den Speicherdienst hochladen möchten.
**Laden Sie Ihre Dateien per Drag & Drop.**
Oder
Durchsuchen
Vorheriger Schritt
Nächster Schritt

**Comment by ChaimaaZaoui** [comment]
tested
