### ISSUE TITLE
[Share Data] Select your data - File Drag and drop

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#241]
As a user, I want to be able to drag and drop files into the service for easy uploading.

### Scenario 1: File drag and drop

**Given that** I am an end user,
**When** I am in _Select your data_ step, 
**Then** a designated area where I can drop files is available,
**And** I should be able to select one or multiple files from my device by clicking and dragging them into the designated area.

**When** dragging the files over the area
**Then** the area takes a hover state

**When** dropping the files
**Then** The files should be automatically selected 

**When** the files are successfully selected
**Then** the files are to be displayed in a list next to the drag and drop section in a list with scroll bar.

**When** new files are added 
**Then** they are shown on the top of the file list

Error management is in : #246 

#### Desktop
![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/ea93a7ae-3490-45e6-ae70-2b52243bbf9a)

![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/710013ad-4930-40d9-9c77-b848e9102662)

### Environment

- staging URL: <https://app.staging.okp4.network/>

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206527159) by [Unito](https://www.unito.io)

**Comment by ErikssonJoakim** [comment]
[drag and drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API)
[drop event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/drop_event)

| Use Case                                                   | Attribute                                         | Description |
| ----------                                                  | -----------                            | ----------- |
| Drag files/folders over area hover state | onDragEnter, onDragLeave | We can use the API to know when to add and remove classNames in className state |
| Drop files/folders & selecting them        | onDrop                                  | onDrop event contains the files dropped as datatransfer objects with a getAsFile method. The selection can be handled in the onDropHandler with a useState hook |

The list will use the selected state to populate itself.

**Comment by ChaimaaZaoui** [comment]
Techspec domain to be done

**Comment by MdechampG** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-board--63e210cc9b1f2f73ee3f4e5f/issues/okp4/dataverse-portal/241?planning-poker) with Zenhub @0xLodz @amimart @ccamel @ErikssonJoakim @fredericvilcot @lolottetheclash

**Comment by ChaimaaZaoui** [comment]
Folders aren't managed in this US, only files are, when a folder is dropped and error message is generated

**Comment by ErikssonJoakim** [comment]
UI component `<FilePicker />` has been merged. Missing the file domain being developed by @fredericvilcot 
- [x] FilePicker UI component
- [ ] File domain

**Comment by ChaimaaZaoui** [comment]
Tested
