### ISSUE TITLE
[Share data] Select your data - Select a file from the explorer 

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#242]
# Feature: [Share data] Select your data - Select a file from the explorer 

As a user, I want to be able to browse my file explorer to select files/folder and upload them into the service.

### Scenario: Select a file from device file explorer 

**Given that** I am an end user,
**When** I am in _Select your data_ step, 
**And** I click on the `browse` button
**Then** a menu opens with 2 options : `Select folders` and `Select files`) 
**When I click on one of the 2 options, 
**Then** the file explorer in my device is launched and I can select either files or folders according to my choice. 

**When** I select one or multiple files/folders
**And** validate the selection from the file/folders explorer
**Then** The files/folders should be automatically selected into the system

**When** the files/folders are successfully uploaded
**Then** the files/folders are to be displayed in a list next to the drag and drop section in a list with scroll bar.

**When** new files/folders are added 
**Then** they are shown on the top of the file list

Error management is in : #246

### Scenario: Internationalisation

EN
Browse
Select files
Select folder

FR
Parcourir
Sélectionner des fichiers
Sélectionner un dossier

GE
durchsuchen
Dateien auswählen
Ordner auswählen

#### Desktop

![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/39e8a602-3d13-41cd-a2e5-dddc29966399)

https://github.com/okp4/product-kanban/assets/115076387/b9322403-fc4d-4684-8263-ba063de3a01f

### Environment

- staging URL: <https://app.staging.okp4.network/>

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206527089) by [Unito](https://www.unito.io)

**Comment by 0xLodz** [comment]
## Techincal specs
Please refer the [technical specs](https://github.com/okp4/dataverse-portal/issues/240#issuecomment-1580491377) from the issue #240.

**Comment by ErikssonJoakim** [comment]
**Technical Specification**

| Use Case | API | description |
| - | - | - |
| User clicks on Browse | [input type="file"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file) | On click the browser opens. With multiple attribute assigned the input field accepts multiple files  |
| file selection | [change event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event), [Zustand updating state](https://docs.pmnd.rs/zustand/guides/updating-state) | When selecting files the onChange event fires allowing us to have a handler that dispatches the event target value to the store |
| Display list of files | [Zustand useStore](https://docs.pmnd.rs/zustand/getting-started/introduction#then-bind-your-components,-and-that's-it!) | The list of files can easily be retrieved from the store |
| Removing a list item | [Zustand updating state](https://docs.pmnd.rs/zustand/guides/updating-state) | When clicking on trash button we can have a handler filter the files selected and set the store to all files selected except the one belonging to the list item. As the store state changes the list will update. |

For the domain see:
- #241

**Comment by ccamel** [comment]
I'd say that the standard approach for providing file and folder selection in a web app is to typically provide two separate buttons, one for file selection and the other for folder selection.

This is what [dropbox](https://dropbox.com/) does in its webapp:

<img width="143" alt="image" src="https://github.com/okp4/dataverse-portal/assets/9574336/17160f51-0eb4-491e-a754-ca62fada65ae">

<img width="298" alt="image" src="https://github.com/okp4/dataverse-portal/assets/9574336/9d99acb0-5a4c-44dd-8371-5c375ddf7b3a">

**Comment by ErikssonJoakim** [comment]
@MdechampG Would this be an option ? We would need to add a button to the mock-up and decide the default behaviour

**Comment by MdechampG** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-board--63e210cc9b1f2f73ee3f4e5f/issues/okp4/dataverse-portal/242?planning-poker) with Zenhub @0xLodz @amimart @ccamel @ErikssonJoakim @fredericvilcot @lolottetheclash

**Comment by ErikssonJoakim** [comment]
UI part is done. File domain in progress:
- https://github.com/okp4/dataverse-portal/issues/241#issuecomment-1611651824

**Comment by ChaimaaZaoui** [comment]
Tested => Failed

The part that failed is when new files/folders are added then they are **NOT** shown on the top of the file list, rather on the bottom.

Can you please fix this part

**Comment by ChaimaaZaoui** [comment]
Tested
