### ISSUE TITLE
[Share data][Share Service] - Start sharing a resource

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#243]
> **As an** end-user of the portal,
> **I want** to chose whether to share data or service 
> **So that** I can start the sharing process 

### Scenario 1 : Chose the resource to share
**Given that** I am an end-user of the portal,
**And** I am using a *desktop* device,
**When** I click on "Share Data & Services" in the sidebar
**Then** two components are displayed on the screen
One allowing to start the share data process, with the following text : 
> I share a dataset
> Easily share your dataset in the dataverse

One allowing to start the share service process, with the following text:
> I share a service
> Easily Share your dataset in the dataverse

### Scenario 2 : Hovering components
**Given that** I am an end-user on the "Share Data & Services" page,
**And** I am using a *desktop* device,

**When** I hover over an available component 
**Then** the BG of the component changes its colour (see mock-up)
**And** the component is clickable

**When** I hover over an unavailable component 
**Then** the BG of the component changes its colour (see mock-up)
**And** the additional information of "Soon Available" is shown
**And** the component is not clickable
_Note for now the 'I share a service' is unavailable_ 

See the video for the hover effect

### Scenario 3: Entering the component 

**When** I click on an available component
**Then** the page of the first step of the process is open

### Scenario 4 : Internationalisation 
ENG
> I share a dataset
> Easily share your dataset in the dataverse

> I share a service
> Easily Share your service in the dataverse
> Soon available 

FR
> Je partage un jeu de données
> Partagez facilement votre jeu de données dans le dataverse

> Je partage un service
> Partagez facilement votre service dans le dataverse
> Bientôt disponible 

DE
> Ich teile einen Datensatz
> Einfaches Freigeben Ihres Datensatzes im Dataverse

> Ich teile einen Dienst
> Einfache Freigabe Ihres Dienstes im Dataverse
> Bald verfügbar 

#### Desktop

![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/9bd74ff7-acdf-422a-9f14-62aa51bf625a)

![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/4cc28ee8-180d-4bff-a2cb-c26721089ae9)

![image](https://github.com/okp4/dataverse-portal/assets/129745194/69e0d913-11e9-4503-90b3-d54e5a3dc528)

https://github.com/okp4/dataverse-portal/assets/129745194/45776600-84b8-40a4-b81b-cd9a6bb69224

### Environment

- staging URL: <https://app.staging.okp4.network/>

## Additional informations

None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206527041) by [Unito](https://www.unito.io)

**Comment by ChaimaaZaoui** [comment]
- [x]  - title, description, and value statement
- [x] - acceptance criteria (scenarios)
- [x] - mock-ups (all devices and themes)
- [x] - labels added
- [x] - US presented to DEV team (refinement)
- [ ] - attached to an epic
- [ ] - estimation (planning poker)
- [x] - external dependencies if applicable

**Comment by ChaimaaZaoui** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-board--63e210cc9b1f2f73ee3f4e5f/issues/okp4/dataverse-portal/243?planning-poker) with Zenhub @0xLodz @amimart @AnjaMis @ccamel @ErikssonJoakim @fredericvilcot @lolottetheclash

**Comment by AnjaMis** [comment]
Waiting for Lisa's medium desktop measurements and review

**Comment by ChaimaaZaoui** [comment]
Tested on desktop => Success
