### ISSUE TITLE
[Share data] Select a storage service - `A local folder` search feature

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#245]
> **As a** As a user in the step "Select a storage service" in `A Local folder`
> **I want** to be able to perform a dynamic text search for item titles so that 
> **So that** I can quickly find relevant storage service based on my search queries.

### Scenario: Dynamic search

**Given that** I am in `A local folder` tab
**And** I am using a *desktop* device,

**When** I type in a text in the search bar, 
**Then** the service cards should dynamically update based on the entered text.
**And** the search results should include all services whose **titles** contain the entered text
**And** the search results should be updated in real-time as I continue to type or modify the text in the search bar.

**When** no matching item titles are found, 
**Then** the search results should display a message indicating "No results found"

#### Desktop
![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/2aced55c-21a6-469f-86f8-21b7f15c9b0a)

### Environment

- staging URL: <https://app.staging.okp4.network/>

## Additional informations

None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206526926) by [Unito](https://www.unito.io)

**Comment by ChaimaaZaoui** [comment]
DOR
- [x] title, description, and value statement
- [x] acceptance criteria (scenarios)
- [x] mockups (all devices and themes)
- [x] labels added
- [x] US presented to DEV team (refinement)
- [ ] attached to an epic
- [ ] estimation (planning poker)
- [x] external dependencies if applicable

**Comment by ChaimaaZaoui** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-board--63e210cc9b1f2f73ee3f4e5f/issues/okp4/dataverse-portal/245?planning-poker) with Zenhub @0xLodz @amimart @AnjaMis @ccamel @ErikssonJoakim @fredericvilcot @lolottetheclash

**Comment by ChaimaaZaoui** [comment]
Add : matching in order and not any character

**Comment by ChaimaaZaoui** [comment]
@fredericvilcot Please share the technical solution

**Comment by ccamel** [comment]
AFAIS, we should use the SPARQL [`contains` predicate](https://www.w3.org/TR/sparql11-query/#func-contains) for filtering. However, to ensure functional and performance aspects, it is necessary to conduct tests on our [fuseki](https://jena.apache.org/documentation/fuseki2/) instance.

**Comment by lolottetheclash** [comment]
**Tech Spec**

UI - medium & large screen only:

No complexity to specify

**Comment by fredericvilcot** [comment]
Regarding the ontology, I'll suggest to add a new filter entry in the `dataverse` domain (e.g `byProperty`)

To be compliant with more properties than only the `title` one, I'll suggest to handle a specific type to query the ontology. This will enable the filtering of all available properties by providing the search bar input value and the property:  

**Type**:

```ts
{
  property: string,
  value: string
}
``` 

**Example**:

```ts
{
  property: "title",
  value: "rhi"
}
``` 

The command will take the `property` and `value` as parameters, that must be checked in the domain part and then call the gateway in reaction or throw an error if parameters are not valid.

In the gateway, we will implement the filter by using the `CONTAIN` method on targeted property with the string value: 

**Example**: 

```ts
FILTER contains(str(?title), "${value}"
```
