### ISSUE TITLE
[Share Data] Fill in the metadata - General display

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#247]
As a user, I want to be able to fill in the metadata of the dataset so that it's properly referenced in the dataverse once uploaded.

### Scenario 1: Dataset metadata
**Given that** I am in the step of "Fill in the metadata",
**And** I am using a _desktop_ device,
**Then** the page is displayed as follows

* **Text**  I SHARE A DATASET
* **Figure** Stepper 
* **Text** Fill in the metadata
* **Text** Please complete the dataset metadata for reference purposes. It is highly discouraged to include personal data in the metadata due to its immutability once stored in the blockchain, which does not comply with GDPR regulations.
* **Fields** see the table below
* Button `< Previous step` always active
* Button `Next step >` active when the mandatory fields are filled

| Field title | Field type |Order | Description | Mandatory |
|----|----|----|----|----|
| Dataset title*  | Text | NA | Title with which the dataset will be referenced in the dataverse | Yes |
| Publisher  | Text | NA | entity primarily responsible for making the resource available | No |
| Creator | Text |NA | Dataset creator's name | No |
| Description | Text | NA | Description of what's contained in the dataset, potential uses, data source... | No |
| Format | Drop-down multiselect list | Alphabetical order | list of media types available in the ontology | No |
| License | Drop-down multiselect list | Alphabetical order | referencing the (major) Open Source licenses. list of licenses available in the ontology | No |
| Topic | Drop-down multiselect list | Alphabetical order | Different common topics, allowing resources to be organised and classified according to their nature or purpose. list of Topics available in the ontology | No |
| Geographical coverage | Drop-down multiselect list | Alphabetical order | origin of data in the dataset, list of areas available in the ontology | No |
| Temporal coverage | Date picker | NA | Time range for data application | No |
| Tags | text | NA | Dataset theme | No |
| Pricing | Numerical field  | NA | The minimum fee applicable for the use of the dataset, the field supports only positive real numbers | No |

_the behaviour of the drop down multiselect list is available in the design system_

### Scenario 2 : Format, License, topic, geographical coverage dropdown behaviour
**Given that** I am in the step of "Fill in the metadata",
**And** I want to fill in Format, License, topic, geographical coverage
**when** open a dropdown
**then** there's a search and a multiselect for the available items

**When** I scroll down the list
**then** there is an infinite scroll and loader 
Fetch 20 by 20

**When** an item is selected
**Then** it is represented as a tag over the dropdown list

**When** the selected items doesn't fit into the field
**then** a clickable tag indicating the number of hidden item is displayed at the end of the field 

**When** I click on the tag displaying the number of hidden items.
**Then** a pop-up page is to be displayed, listing the items
see the US of the pop-up in : #218

### Scenario 3 : Inserting Tags
**Given that** I am in the step of "Fill in the metadata",
**And** want to fill in multiple tags
**when** I write down the first tag
**And** I press the enter key on my keyboard
**then** the first tags is entered and highlighted 
**and** I can start writing the following tag

**When** many tags are filled in
**Then** the height of the tag field can increase accordingly
**And** stops just above the pricing area

#### Additional details for Inserting Tags v1

* Maximum tag field is two lines long
* Starts on one line, if the tags entered require more space, then a first automatic line feed takes place.
* If the second line is filled, a scroll bar is added to access the third line, and so on. (but always two lines displayed).
* When the third tag line is entered, the input will not be centered on the input element (this is the default behavior), so there's no need to improve the behavior in order to center on the input, as the scroll bar only represents V1, and will subsequently be replaced by [the "+n" button and the modal] in the same way as the "format, license, topic" fields.

### Scenario 4: Temporal coverage
**Given that** I am in the step of "Fill in the metadata",
**And** want to fill in the temporal coverage
**Then** by default it's an empty field

**When** I select a date picker field
**then** the calendar is focused on today's date

**when** I select a start date first
**Then** the end date must the same date or a later date (non applicable date are to be hidden)

**When** I enter an end date first
**Then** the start date must be the same date or a previous date (non applicable date are to be hidden)

_Please be aware that the date fields are optional, allowing for either the start date or the end date to be filled in, but not necessarily both._

### Scenario 5 : Price formatting
Given that I am in the price field,
And I enter the numbers for the price,
Then as I type, each group of three numbers must be automatically separated by a space.

Given that I want to enter decimal values,
When I input a comma or a full stop,
Then the UI should consistently display a full stop as the decimal separator.
see : https://app.uniswap.org/#/swap

Given that the smallest decimal unit is microKnow (10 to the power of -6),
When I enter a decimal value,
Then only 6 digits after the decimal point are accepted

### Scenario 5 : Internationalisation 
ENG
> Fill in the metadata
>Please complete the dataset metadata for reference purposes. It is highly discouraged to include personal data in the metadata due to its immutability once stored in the blockchain, which does not comply with GDPR regulations.
> Dataset title
> Publisher
> Creator
> Description
> Format // Select format
> License // Select License 
> Topic // Select topic
> Geographical coverage // Select geographical coverage
> Temporal coverage
> Tags // Type and press enter
> Enter the minimum fee applicable for the use of this dataset
> KNOW

FR
> Renseigner les métadonnées
> Saisir les métadonnées de l'ensemble de données à référencer. Il est fortement déconseillé d'utiliser des données personnelles dans les métadonnées, car elles sont immuables une fois dans la blockchain et ne sont pas conformes au RGPD.
> Titre du jeu de données
> Éditeur
> Créateur
> Description
> Format // Sélectionner le format
> Licence // Sélectionner la licence 
> Thème// Sélectionner le thème
> Couverture géographique // Sélectionner la couverture géographique
> Couverture temporelle
> Tags // Tapez et appuyez sur entrée
> Saisir la redevance minimale applicable à l'utilisation de ce jeu de données
> KNOW

DE

> Füllen Sie die Metadaten aus
> Bitte füllen Sie die Metadaten des Datensatzes zu Referenzzwecken aus. Es wird dringend davon abgeraten, personenbezogene Daten in die Metadaten aufzunehmen, da sie unveränderlich sind, sobald sie in der Blockchain gespeichert sind, was nicht den GDPR-Vorschriften entspricht.
> Titel des Datensatzes
> Herausgeber
> Ersteller
> Beschreibung
> Format // Format auswählen
> Lizenz // Lizenz auswählen
> Thema // Thema auswählen
> Geografische Abdeckung // Wählen Sie die geografische Abdeckung
> Zeitliche Abdeckung
> Tags // Tippen Sie und drücken Sie die Eingabetaste
> Geben Sie die Mindestgebühr für die Nutzung dieses Datensatzes ein
> KNOW

#### Desktop
Empty : 
![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/ab736797-09a2-407a-b740-9194777d913c)

Filled:
![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/072ad5fa-2ab7-441a-a3d4-ac57ded0fbfa)

Dropdown + multiselect 
![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/0adb324d-7712-47e8-a12c-dbc975afcfc6)

### Environment

* staging URL: <https://app.staging.okp4.network/>

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206526787) by [Unito](https://www.unito.io)

**Comment by ChaimaaZaoui** [comment]
- [x]  - title, description, and value statement
- [x] - acceptance criteria (scenarios)
- [x] - mock-ups (all devices and themes)
- [x] - labels added
- [ ] - US presented to DEV team (refinement)
- [ ] - attached to an epic
- [ ] - estimation (planning poker)
- [x] - external dependencies if applicable

**Comment by 0xLodz** [comment]
## Technical Specifications

### Dropdown + multiselect
Creation of this component from the design system that includes:
#### Existing components
- Collapsible
- SearchBar
- DynamicCheckbox
#### Missing components
- Closable label -> From the Tag component that already exists, with a **X** button.

---

### Tags input
#### Missing components
- Closable label -> From the Tag component that already exists, with a **X** button.

---
### Form

#### Comparing form libraries

Here is a comparison of three form libraries: [Formik](https://formik.org/), [React Final Form](https://final-form.org/react), and [React Hook Form](https://www.react-hook-form.com/). The comparison is based on several criteria such as performance, ease of implementation, community usage, and size.

| Criteria | Formik | React Final Form | React Hook Form |
| --- | --- | --- | --- |
| Performance | Good, but may have more re-renders | Very good, minimal re-renders | Excellent, minimizes re-renders |
| Ease of Implementation | Moderate, a bit of boilerplate | High, less boilerplate | High, minimal boilerplate |
| Community Usage | Very high, large community | Moderate, less usage compared to Formik and RHF | High, fastest-growing library |
| Size | Moderate, larger than RFF and RHF | Small, smallest of the three | Small, smaller than Formik |
| Validation Library Compatibility | High, seamless integration with Yup | Moderate, requires additional setup | High, compatible with Zod and Yup |

### Chosen solution
Based on the comparison above and the requirements of the project, the chosen solution for managing form state might be:
- **Form Library**: [React Hook Form](https://www.react-hook-form.com/): high performance, easy implementation, growing community.
- **Form Validation**: [Zod](https://zod.dev/): robust and comprehensive validation, excellent integration with React Hook Form. Good alternative: [Yup](https://www.npmjs.com/package/yup)

#### Reasons for picking RHF
- **Performance**: RHF minimizes re-renders, leading to better performance, especially for complex forms with many interactions.
- **Ease of Implementation**: RHF requires minimal boilerplate code, making it simpler and faster to implement.
- **Growing Community**: RHF is the fastest-growing form library, indicating that it's being widely adopted and actively maintained.
- **Size**: RHF is smaller than Formik, making it a better choice for keeping the JavaScript bundle size low.
- **Validation**: RHF is compatible with [Zod](https://zod.dev/) and [Yup](https://www.npmjs.com/package/yup), two powerful validation libraries.

### Basic form's implementation, based on the [Stepper's technical spec](https://github.com/okp4/dataverse-portal/issues/236#issuecomment-1578757452).
```tsx
const Step: React.FC<StepProps> = ({ title }) => {
  const validateStep = useContext(ValidateStepContext)
  const stepSchema = z.object({
    field1: z.string().min(3),
    field2: z.string().min(3)
  })
  const {
    register,
    formState: { errors, isValid },
    trigger
  } = useForm({
    mode: 'onChange',
    resolver: zodResolver(stepSchema)
  })

  useEffect(() => {
    const validateFields = async (): Promise<void> => {
      await trigger()
      validateStep(isValid)
    }

    validateFields()
  }, [trigger, validateStep, isValid])

  return (
    <form>
      <h2>{title}</h2>
      <input {...register('field1')} name="field1" />
      {errors.field1 && <p>{errors.field1.message?.toString()}</p>}
      <input {...register('field2')} name="field2" />
      {errors.field2 && <p>{errors.field2.message?.toString()}</p>}
    </form>
  )
}
```


### Sources
- https://blog.logrocket.com/react-hook-form-vs-formik-comparison/
- https://dev.to/sm0ke/react-forms-formik-vs-hook-form-vs-final-form-c1e

**Comment by ChaimaaZaoui** [comment]
I have update the price formatting for share data as well.

**Comment by lmarline** [comment]
@ChaimaaZaoui hi can you change the translation for german? Thanks to the following bold text below:

Füllen Sie die Metadaten aus
**Bitte füllen Sie die Metadaten des Datensatzes zu Referenzzwecken aus. Es wird dringend davon abgeraten, personenbezogene Daten in die Metadaten aufzunehmen, da sie unveränderlich sind, sobald sie in der Blockchain gespeichert sind, was nicht den GDPR-Vorschriften entspricht.**
Titel des Datensatzes
Herausgeber
Ersteller
Beschreibung
Format // Format auswählen
Lizenz // Lizenz auswählen
Thema // Thema auswählen
**Geografische Abdeckung // Wählen Sie die geografische Abdeckung
Zeitliche Abdeckung**
Tags // Tippen Sie und drücken Sie die Eingabetaste
Geben Sie die Mindestgebühr für die Nutzung dieses Datensatzes ein
_**Preisgestaltung**_ (delete pricing as we said)
KNOW

**Comment by ChaimaaZaoui** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-board--63e210cc9b1f2f73ee3f4e5f/issues/okp4/dataverse-portal/247?planning-poker) with Zenhub @0xLodz @AnjaMis @fredericvilcot @ErikssonJoakim

**Comment by SpicySalm0n** [comment]
@0xLodz I was more thinking about convert dropdown in dropup when the space is not enough. The search bar would still be hooked to the original input so up or down:
<img width="550" alt="Capture d’écran 2023-07-11 à 17 40 26" src="https://github.com/okp4/dataverse-portal/assets/115076387/78a10a12-0d65-4256-a988-e647040f9dca">

For the animation, I don't think we should do the same since there is 2 distincts containers. I was thinking about something like this, what do you think? is it possible?

Animation example: https://dev.to/mmmrks/building-a-vuejs-dropdown-menu-component-ho3

**Comment by 0xLodz** [comment]
@SpicySalm0n Yes, this could be a good way of keeping collapsible content accessible without impacting the way the layout is displayed!

**Comment by ChaimaaZaoui** [comment]
Tested
