### ISSUE TITLE
[Share Data] All in summary - General display

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#248]
As a user, I want to be able to read the summary of dataset sharing process so that I can edit any information before proceeding to the payment 

### Scenario 1: Metadata and file overview

**Given that** I am in the step of "All in summary",
**And** I am using a *desktop* device,

**Then** I can have an overview of the files I selected in my dataset
**And** the the metadata I filled for the dataset 
**And** the page is displayed as follows

- **Text**  _I SHARE A DATASET_
- **Figure** Stepper 
- **Text** _All in summary_
- **Metadata section ** + scroll bar
-- Dataset title, Publisher, Creator, Description, format, license, topic, geographical coverage, temporal coverage, tags
- **List** of files, with a scroll bar if the list doesn't fit within the designated area
- **Price field** + **Text** _Fee set for the use of this dataset_
- **Checkbox** + **Text** _I certify that I do not share any personal metadata._ 
- Button `< Previous step` always active
- Button `Next step >` active when the checkbox is ticked

### Scenario 2 : Internationalisation 
ENG
> All in summary

> Dataset title
> Publisher
> Creator
> Description
> Format
> License 
> Topic
> Geographical coverage
> Temporal coverage
> Tags 

> Fees set for the use of the dataset

> I certify that I do not share any personal metadata

FR
> Récapitulatif

> Titre du jeu de données
> Éditeur
> Créateur
> Description
> Format
> Licence 
> Thème
> Couverture géographique
> Couverture temporelle
> Tags 

> Redevances liées à l'utilisation des données

> Je certifie que je ne partage aucune métadonnée personnelle.

DE
> Zusammenfassung 

> Titel des Datensatzes
> Herausgeber
> Ersteller
> Beschreibung
> Format
> Lizenz 
> Thema
> Geografische Abdeckung
> Zeitliche Abdeckung
> Tags 

> Gebühren für die Nutzung der Daten

> Ich bestätige, dass ich keine persönlichen Metadaten weitergebe.

#### Desktop
![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/967a3d3a-6214-45b0-9107-acd00a99adda)

### Environment

- staging URL: <https://app.staging.okp4.network/>

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206526720) by [Unito](https://www.unito.io)

**Comment by ChaimaaZaoui** [comment]
- [x]  - title, description, and value statement
- [x] - acceptance criteria (scenarios)
- [x] - mock-ups (all devices and themes)
- [x] - labels added
- [ ] - US presented to DEV team (refinement)
- [ ] - attached to an epic
- [ ] - estimation (planning poker)
- [x] - external dependencies if applicable

**Comment by MdechampG** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-board--63e210cc9b1f2f73ee3f4e5f/issues/okp4/dataverse-portal/248?planning-poker) with Zenhub @0xLodz @amimart @ccamel @ErikssonJoakim @fredericvilcot @lolottetheclash

**Comment by lolottetheclash** [comment]
Do not forget to add add inifinite scroll for metadata display on `DetailedDataverseItem`.

**Comment by lmarline** [comment]
@ChaimaaZaoui hi can you change the translation in german please ? Just the following bold text:

**Zusammenfassung** instead of "Alles in Kürze"

**Comment by AnjaMis** [comment]
@ChaimaaZaoui is it so that if the checkbox is not checked you cannot proceed to the next step? Also, are users obligated to select files/folders or is that an optional feature? Just asking to check if the file list will always be displayed in this step or not :) Thanks!

**Comment by ChaimaaZaoui** [comment]
@AnjaMis 

- the checkbox is mandatory to be able to move to the next step, if not checked the next button should not be clickable
- at least one file must be selected to move to the metadata step, if no file is selected the next button should not be clickable

**Comment by ChaimaaZaoui** [comment]
tested OK
