### ISSUE TITLE
Catalog grid content - Card content

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#272]
| Test case | Expected result | status | Actual result |
| ----------- | ----------- | ----------- | ----------- |
| I navigate the .../dataverse | each card must contain the title and the topic (for data spaces and datasets) or the category (for services)| Failed| The card shows the title and the description |

Problem encountered both on Mobile and Desktop

**Comment by fredericvilcot** [comment]
@ChaimaaZaoui @ccamel 
Topics and Categories objects are represented in the ontology with simple strings that can contain one or several words in **PascalCase** convention.
E.G: **_"https://ontology.okp4.space/thesaurus/topic/AgricultureEnvironmentAndForestry"_**

On other hand, in the mock up, we want to add some punctuation (commas) and remove capitals for words that act only as a separator (like **and** word): 
![Capture d’écran 2023-06-07 à 15.14.01.png](https://images.zenhubusercontent.com/6239e03463de653dd1b23cc9/ea830c05-ddc5-45f6-8933-77d1465f8593)

Is this the definitive format in the ontology or is it planned to add commas or ponctuation manually in the object?

**Comment by fredericvilcot** [comment]
@ChaimaaZaoui 
Fix is deployed in staging to test

**Comment by ChaimaaZaoui** [comment]
Tested on windows, firefox, bug fixed 👍🏽

**Comment by AnjaMis** [comment]
@jeremylgn
