### ISSUE TITLE
[SHARE DATA] Feature not available on small devices 

### ISSUE THREAD

**Issue by lolottetheclash** [okp4/dataverse-portal#317]
As a user, I am navigating on the app with a tablet or mobile
I want to be informed that this feature is only available on medium or large screen
So that I can continue to share data with appropriate device.

## Acceptance criteria

**Given that** I am using a mobile or tablet,
**And** I am navigating to "Share" page,

**Then** I have a special display to inform me that this feature is not available
**And** a "Go to the homepage button" is also available to keep navigating.

### Scenario 2 : Internationalisation 
ENG
Sorry,
Feature not supported on tablet
Feature not supported on mobile
Please switch to your computer.
Go to homepage

FR
Désolé,
Fonctionnalité non prise en charge sur tablette
Fonctionnalité non prise en charge sur mobile
Veuillez basculer vers votre ordinateur.
Aller à la page d'accueil

DE
Entschuldigung,
Funktion wird auf dem Tablet nicht unterstützt
Funktion wird auf dem Handy nicht unterstützt
Bitte wechseln Sie zu Ihrem Computer.
Zur Homepage gehen

### Mockups

![mocks.png](https://images.zenhubusercontent.com/62aa0d2704bd8f5167ff33b3/8e677c39-ead5-4a60-87e2-57dba9013b16)

### Environment

- staging URL: <https://app.staging.okp4.network/>

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206526018) by [Unito](https://www.unito.io)

**Comment by ChaimaaZaoui** [comment]
Tested on desktop => Success
Tested on Mobile=> Success
