### ISSUE TITLE
[Dataverse] search feature

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#336]
> **As a** As a user in the Dataverse page
> **I want** to be able to perform a dynamic text search for resource titles so that 
> **So that** I can quickly find relevant resource based on my search queries.

### Scenario: Dynamic search

**Given that** I am in Dataverse page
**And** I am using a **any** device,

**When** I type in a text in the search bar, 
**Then** the resource cards should dynamically update based on the entered text.
**And** the search results should include all resources whose **titles** contain the entered text
**And** the search results should be updated in real-time as I continue to type or modify the text in the search bar.

**When** no matching item titles are found, 
**Then** the search results should display a message indicating "No results found"

### Scenario: Internationalisation
Eng
Search in this dataverse
No results found

FR
Recherche dans ce dataverse
Aucun résultat trouvé

DE
Suche in diesem Dataverse
Keine Ergebnisse gefunden

#### Desktop
![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/2099d094-2f1e-47de-bd60-178bfc58b849)

### Environment

- staging URL: <https://app.staging.okp4.network/>

## Additional informations

None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206525834) by [Unito](https://www.unito.io)

**Comment by fredericvilcot** [comment]
The logic part has already been implemented in the `Share Data` feature.

So, there is only the `SearchBar` component to add and to style regarding the existing `Explore` page.

**Comment by ChaimaaZaoui** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-board--63e210cc9b1f2f73ee3f4e5f/issues/okp4/dataverse-portal/336?planning-poker) with Zenhub @0xLodz @AnjaMis @ErikssonJoakim @fredericvilcot
