### ISSUE TITLE
Feature: Lateral bar

### ISSUE THREAD

**Issue by ccamel** [okp4/dataverse-portal#34]
# Feature: Lateral bar

> **As a** user of the portal,
> **I want** to have a collapsible lateral bar on the left-hand side of the screen that contains navigation links and social network links, as well as a switcher for dark/light mode
> **So that** it allows me to quickly access important information and easily switch between different themes.

### Scenario: default display (desktop)

**Given that** I am a user of the web portal,
**And** I am using a *desktop* device,
**When** I access any page of the portal,
**Then** The lateral bar should be expanded on the left-hand side of the screen,
**And** should display navigation links to various sections of the portal (see mockup), social media links, and a button for sending feedback.
**And** should have the light theme selected.

### Scenario: collapse/expand

**Given that** I am a user of the web portal,
**When** I click the collapse icon on the expanded lateral bar,
**Then** the lateral bar should collapse and hide the navigation links and social network links, making more space available for the content area of the page (see mockup).
**When** I click the collapse icon of the collapsed lateral bar,
**Then** the lateral bar should expand on the left-hand side of the screen
**And** should display navigation links to various sections of the portal (see mockup), social media links, and a button for sending feedback.
**And** the lateral bar state (collapsed / expanded) is persisted in the browser for the next session.

### Scenario: theme switching

**Given that** I am a user of the web portal,
**When** I click the theme switcher button,
**Then** the theme of the entire portal should change to the alternate theme.
**And** the switcher button should visually reflect the currently selected theme.
**And** the theme is persisted in the browser for the next session.

### Scenario: links

**Given that** I am a user of the web portal,
**When** I click on the link: `Home`,
**Then** the portal should navigate to `/` and display a `Work In Progress` page
**When** I click on the link: `Explore`,
**Then** the portal should navigate to `/catalog` and display a `Work In Progress` page
**When** I click on the link: `My Data Spaces`,
**Then** the portal should navigate to `/dataspace` and display a `Work In Progress` page
**When** I click on the link: `Share Data & Services`,
**Then** the portal should navigate to `/sharing` and display a `Work In Progress` page
**When** I click on the link: `Create Knowledge`,
**Then** the portal should navigate to `/knowledge-builder` and display a `Work In Progress` page
**When** I click on the link: `Create Dataspace`,
**Then** the portal should navigate to `/dataspace-builder` and display a `Work In Progress` page
**When** I click on the link: `Build Applications`,
**Then** the portal should navigate to `/app-builder` and display a `Work In Progress` page
**When** I click on the link: `Documentation`,
**Then** the portal should navigate to `/documentation` and display a `Work In Progress` page
**When** I click on the link: `Help Center`,
**Then** the portal should navigate to `/help` and display a `Work In Progress` page
**When** I click on the `Twitter` icon,
**Then** the portal should open <https://twitter.com/OKP4_Protocol> in another tab.
**When** I click on the `LinkedIn` icon,
**Then** the portal should open <https://www.linkedin.com/company/okp4-open-knowledge-platform-for> in another tab.
**When** I click on the `Discord` icon,
**Then** the portal should open <https://discord.com/invite/okp4> in another tab.
**When** I click on the `Medium` icon,
**Then** the portal should open <https://blog.okp4.network/> in another tab.
**When** I click on the `About OKP4` link,
**Then** the portal should open <https://okp4.network> in another tab.
**When** I click on the `Give us feedback` link,
**Then** the portal should open to <https://okp4.typeform.com/to/TNyFBH72> in another tab.

## Requirements

None.

### Mockups

![image](https://user-images.githubusercontent.com/9574336/219097068-6737ca5c-c6dd-4ffd-a17b-138b40d68e69.png)

### Environment

- staging URL: <https://app.staging.okp4.network/>

## Additional informations

None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206529750) by [Unito](https://www.unito.io)

**Comment by MdechampG** [comment]
16/02/23

Tested on Mozilla Firefox (desktop).
Scenario default display : OK except from the font of the titles (seen with @fredericvilcot it will be okay soon). 
Scenario Collapse / Expand : OK
Scenario theme switching : OK
Scenario Links : OK for social media (even with collapsed bar) but not for the other links (to test later on)

**Comment by MdechampG** [comment]
I have added in the description of the issue the link for the `Give us feedback` button towards a typeform.

**Comment by fredericvilcot** [comment]
@MdechampG 
FYI the associated pull request is opened and on review.

**Comment by MdechampG** [comment]
20/02/23

Tested on Mozilla Firefox (desktop).
Scenario default display : OK ✅ 
Scenario Collapse / Expand (with persistence) : OK ✅ 
Scenario theme switching (with persistence) : OK ✅ 
Scenario Links : OK ✅ 

LGTM !
