### ISSUE TITLE
[Portal] Button behaviour

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#345]
As a user, I want a button with four states (Default, Hover, Pressed, and Disabled) so that I can interact with it effectively.

### Scenario 1: Button behaviour

Given a button with four states (Default, Hover, Pressed, and Disabled),

When the button is in the Default state, 
Then I can see the label and it appears clickable.

When I hover over the button
Then it transitions to the Hover state as designed.

**When I click on the button while in the Hover state, 
Then it transitions to the Pressed state the few micro seconds until the action behind the button is executed.
And If I release the mouse button while in the Pressed state, the button returns to the Default state.** 

When in the Disabled state, 
Then the button's appearance indicates it cannot be interacted with, and clicking is not possible.

_This is applicable to buttons, and to cards that have a button behaviour
Please go through the whole application to make sure that all buttons have the 4 states_

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206525668) by [Unito](https://www.unito.io)

**Comment by fredericvilcot** [comment]
For now, it only misses the `pressed` state that must be implemented in the generic `Button` component.

**Comment by ChaimaaZaoui** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-board--63e210cc9b1f2f73ee3f4e5f/issues/okp4/dataverse-portal/345?planning-poker) with Zenhub @0xLodz @AnjaMis @ErikssonJoakim @fredericvilcot

**Comment by ChaimaaZaoui** [comment]
Tested on desktop => Success
Tested on mobile => Success
