### ISSUE TITLE
[Share Data] Select your data - Folder Drag & Drop

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#351]
As a user, I want to be able to drag and drop folders into the service for easy uploading.

### Scenario 1: Folder drag and drop

**Given that** I am an end user,
**When** I am in _Select your data_ step, 
**Then** a designated area where I can drop folders / files is available,
**And** I should be able to select **one or multiple folders** from my device by clicking and dragging them into the designated area.

**When** dragging the folder over the area
**Then** the area takes a hover state

**When** dropping the folder 
**Then** The folder should be automatically selected 

**When** the folder are successfully selected
**Then** the **files available in the folder are to be displayed** in a list with a scroll bar next to the drag and drop section.

**When** new files are added 
**Then** they are shown on the top of the file list

Error management is in : #246 

#### Desktop
![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/ea93a7ae-3490-45e6-ae70-2b52243bbf9a)

![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/710013ad-4930-40d9-9c77-b848e9102662)

### Environment

- staging URL: <https://app.staging.okp4.network/>

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206525513) by [Unito](https://www.unito.io)

**Comment by lolottetheclash** [comment]
@MdechampG & @ChaimaaZaoui we have to think about a loader when loading large amount of files and also a remove all files button to improve use experience

**Comment by ChaimaaZaoui** [comment]
@lolottetheclash definitely, I will take that as an improvement for our V2

**Comment by ChaimaaZaoui** [comment]
tested ok
