### ISSUE TITLE
Share data page and stepper layout

### ISSUE THREAD

**Issue by 0xLodz** [okp4/dataverse-portal#365]
Bug 1: The layout doesn't corresponds to the mockups.
-> Card details must me displayed at the same level as the search bar.

Bug 2: When a service card is selected, the whole stepper content scrolls, including titles and search bar. These elements are then hidden an no more accessible.
-> An alternative scrolling mechanism must be used to display the card in the view.

Bug 3: The bottom of content of the card and card details are truncated on small desktop screens.
-> Update the stepper layout in order to it's content height to fit the available space.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206525459) by [Unito](https://www.unito.io)

**Comment by ChaimaaZaoui** [comment]
Seen with @0xLodz , OK to close
