### ISSUE TITLE
[Share data] Complete Tx - General display

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#427]
As a user, I want to be able to proceed to the payment of the referencing fees so that my dataset goes through the validation process

### Scenario 1: Transaction step
**Given that** I am in the step of "Complete the transaction",
**And** I am using a _desktop_ device,
**Then** the page is displayed as follows

* **Text**  I SHARE A DATASET
* **Figure** Stepper 
* **Text** Complete the transaction
* **Text** Shared dataset
* Name of the dataset
* Fee Section
* Button `< Previous step` always active

### Scenario 2: Dataset name
**Given** that I entered a dataset name in the metadata step
**Then** this name should be displayed in dataset name field.

### Scenario 3: Internationalisation
ENG

> Complete the transaction
> Shared Dataset
> Fee estimation
> to reference your dataset into the protocol
> Proceed to the payment on

FR

> Finaliser la transaction
> Jeu de données partagé
> Estimation des frais
> pour référencer votre jeu de données dans le protocole
> Procéder au paiement sur

DE

> Die Transaktion abschließen
> Gemeinsamer Datensatz
> Kostenschätzung
> um Ihren Datensatz im Protokoll zu referenzieren.
> Nehmen Sie die Zahlung vor auf

#### Desktop
![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/e4e3676b-df29-4907-b35d-2167c6e2b340)

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206524625) by [Unito](https://www.unito.io)

**Comment by ChaimaaZaoui** [comment]
- name of the dataset
- large screen device

**Comment by 0xLodz** [comment]
## Tech specs
Paiement & fees estimation are not part of this issue.


- create a sharedata step 5
- retrieve saved dataset name
- use the [tooltip](https://www.radix-ui.com/primitives/docs/components/tooltip) component from radix to display dataset info.

**Comment by 0xLodz** [comment]
@ChaimaaZaoui could we get translations for the following tooltip content ?

> This fee consists only of gas fees. This is an estimation based on the current network conditions and the complexity of the transaction.

> Please note:
The gas fee ensures your transaction gets processed on the blockchain network.
If the actual gas fees required exceed the estimated amount, the transaction will be declined. Otherwise, it will be validated.
You will only be charged for the exact gas fees spent during the transaction.

> Additionally, the maximum processing time for a new block is 10 seconds. Your transaction will be included in an available block based on the gas price you choose.

> Make sure to review the gas price carefully to optimize transaction speed and costs.

**Comment by lolottetheclash** [comment]
@0xLodz you can put this ticket in the to do column, @ChaimaaZaoui will give you the missing translations to achieve the UI part👍

**Comment by 0xLodz** [comment]
@ChaimaaZaoui @lolottetheclash sorry for the inconvenience, I just found the issue #432 with all translations.

I suggest to separate both issues as such:
- this issue that integrates the step content (not wired to ontology), including tooltip's content
- the issue #432 that consist of building a tooltip component, with the style related to our design system.

Are you ok with these updates? If so, we can update and create tech specs accordingly.

Thanks

**Comment by ChaimaaZaoui** [comment]
@0xLodz translations updated

**Comment by ChaimaaZaoui** [comment]
tested
