### ISSUE TITLE
[Share data] Complete Tx  - Fee section

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#432]
As a user, I want to be able to proceed to the payment of the referencing fees so that my dataset goes through the validation process

### Scenario 1: Fee section
**Given that** I am in the step of "Complete the transaction",
**And** I am using a _desktop_ device,
**Then** the fee section is displayed as follows

* Text:  Fee section
* Transaction value 
* Information tooltip
* Text: To reference your dataset into the protocol 
* Button: Proceed to the payment on Keplr 

### Scenario 2: Fee Estimation
**Given that** I am on the web3 transaction page,
**Then** the page should calculate and display an estimated gas fee in tokens based on the current network conditions and the complexity of the transaction.

As a V1 of this scenario, the same fixed fee will always be displayed. See with A.M. to determine this value.

### Scenario 3: Information tooltip
When I hover over on the `i ` button,
Then a tooltip should appear, clarifying that :

> This fee consists only of gas fees. This is an estimation based on the current network conditions and the complexity of the transaction.
> 
> Please note:
> The gas fee ensures your transaction gets processed on the blockchain network.
> If the actual gas fees required exceed the estimated amount, the transaction will be declined. Otherwise, it will be validated.
> You will only be charged for the exact gas fees spent during the transaction.
> 
> Additionally, the maximum processing time for a new block is 10 seconds. Your transaction will be included in an available block based on the gas price you choose.
> 
> Make sure to review the gas price carefully to optimize transaction speed and costs.

**When** there's not enough space to display the tooltip on the right of the i button, 
**Then** display it where ever you have space on the screen, top, bottom , left..

### Scenario 4: Payment button
Given that I want to proceed with the payment of the displayed fees
When I click on the `Proceed to the payment on Keplr`
Then Keplr is to be launched to validate the payment

_As a user, I will follow Keplr instruction to connect my wallet and validate the transaction if my balance allows it. The user journey on keplr will not be detailed here._

### Scenario 5: Internationalisation
FR
Estimation de frais
Pour référencer votre dataset dans le protocole
Procéder au paiement sur Keplr

> Ces frais ne comprennent que les frais de gaz. Il s'agit d'une estimation basée sur les conditions actuelles du réseau et la complexité de la transaction.
> 
> Veuillez noter :
> Les frais de gaz garantissent le traitement de votre transaction sur le réseau blockchain.
> Si les frais de gaz réels requis dépassent le montant estimé, la transaction sera refusée. Dans le cas contraire, elle sera validée.
> Vous ne serez facturé que pour les frais de gaz exacts dépensés au cours de la transaction.
> 
> En outre, le temps de traitement maximum d'un nouveau bloc est de 10 secondes. Votre transaction sera incluse dans un bloc disponible en fonction du prix de gaz que vous avez choisi.
> 
> Veillez à examiner attentivement le prix de gaz afin d'optimiser la vitesse et les coûts de la transaction.

DE

Honorarvoranschlag
Ihren Datensatz im Protokoll zu referenzieren
Fahren Sie mit der Zahlung auf Keplr fort

> Diese Gebühr besteht nur aus den Gasgebühren. Es handelt sich um eine Schätzung auf der Grundlage der aktuellen Netzbedingungen und der Komplexität der Transaktion.
> 
> Bitte beachten Sie:
> Die Gasgebühr stellt sicher, dass Ihre Transaktion über das Blockchain-Netzwerk abgewickelt wird.
> Wenn die tatsächlich erforderlichen Gasgebühren den geschätzten Betrag übersteigen, wird die Transaktion abgelehnt. Andernfalls wird sie validiert.
> Ihnen werden nur die exakten Gasgebühren in Rechnung gestellt, die während der Transaktion ausgegeben werden.
> 
> Außerdem beträgt die maximale Bearbeitungszeit für einen neuen Block 10 Sekunden. Ihre Transaktion wird in einen verfügbaren Block aufgenommen, der auf dem von Ihnen gewählten Gaspreis basiert.
> 
> Überprüfen Sie den Gaspreis sorgfältig, um die Transaktionsgeschwindigkeit und die Kosten zu optimieren.

#### Desktop
![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/b1713469-f4f9-4bd0-b6c2-ffa69720d838)

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206524529) by [Unito](https://www.unito.io)

**Comment by 0xLodz** [comment]
## Tech specs

- fetch blockchain data that allow to estimate current dataset fees

- create a tooltip component, based the [tooltip](https://www.radix-ui.com/primitives/docs/components/tooltip) component from radix and our design system
- integrate the tooltip to displayed translated info

**Comment by 0xLodz** [comment]
@amimart fee amount will be hardcoded for the V1 of the payment page. Do you have any idea of what amount it would be? Thanks!

**Comment by amimart** [comment]
> @amimart fee amount will be hardcoded for the V1 of the payment page. Do you have any idea of what amount it would be? Thanks!

It's hard to imagine at the moment, but it's not a big deal as through the wallet payment interfaces the user will be able to change the maximum fee he allow for the transaction to succeed.

If you really need an estimation let's say `1000000uknow` which corresponds to `1 $KNOW`. but we may consider making this value customizable through configuration instead of hardcoding it so we can easily update it, transaction costs are likely to change over time because of evolutions on the protocol.

**Comment by ChaimaaZaoui** [comment]
V1 tested ok
