### ISSUE TITLE
Feature: internationalization

### ISSUE THREAD

**Issue by fredericvilcot** [okp4/dataverse-portal#46]
# Feature: Internationalization
> **As a** user of the portal,
> **I want**  to see English texts for the lateral bar
> **So that** it allows me to navigate through the app in my favorite language

### Scenario: lateral bar translations
**Given that** I am a user of the web portal,
**When** I access any page of the portal,
**Then** The lateral bar texts should be displayed in English language,
**Given that** I am a user of the web portal,
**When** I expand the lateral bar,
**Then** navigation items must be displayed in english: 
`General`
`Home`
`Explore`
`My Data Spaces`
`Interact`
`Share Data & Services`
`Create Knowledge`
`Create Data Spaces`
`Build Applications`
`Learn`
`Documentation`
`Help Center`
**Given that** I am a user of the web portal,
**When** I expand the lateral bar,
**Then** footer items must be displayed in english: 
`Give us feedback`
`About OKP4`

### Scenario: work in progress page translations
**Given that** I am a user of the web portal,
**When** I click on any navigation item
**Then** a work in progress page is displayed
**And** that displays English texts:
`Work In Progress`
`We are working hard to unleash the Dataverse, stay tuned! 🚀`

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206530007) by [Unito](https://www.unito.io)

**Comment by fredericvilcot** [comment]
@MdechampG 
This issue implements the global internationalization for the whole app.
For now, all texts are displayed in English, available for new languages (FR, DE, etc..)

**Comment by fredericvilcot** [comment]
@MdechampG 
This feature is available on staging

**Comment by MdechampG** [comment]
Validated ✅
