### ISSUE TITLE
Feature: Connect wallet

### ISSUE THREAD

**Issue by fredericvilcot** [okp4/dataverse-portal#47]
# Feature: Connect wallet

> **As a** user of the portal,
> **I want** to have a `connect my wallet` button in the toolbar at the top of the screen
> **So that** it allows me to quickly connect my wallet

### Scenario: default display (desktop)

**Given that** I am a user of the web portal,
**And** I am using a *desktop* device,
**When** I access any page of the portal,
**Then** I should see a `connect my wallet` button in the toolbar
**And** should be thematized regarding the selected theme
**And** should do nothing for now when I click on the `connect my wallet` button.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206530060) by [Unito](https://www.unito.io)

**Comment by fredericvilcot** [comment]
@MdechampG 
FYI

**Comment by fredericvilcot** [comment]
@MdechampG 
This feature is available on staging environment.

**Comment by MdechampG** [comment]
Tested on Firefox ans Safari 
✅ Visible on all pages 
✅ thematization 
✅ change color when hover
✅ Nothing happens when we click on it
