### ISSUE TITLE
Feat : Resource Detail - General metadata

### ISSUE THREAD

**Issue by MdechampG** [okp4/dataverse-portal#69]
# Feat : Resource Detail - General metadata

> **As a** user of the portal,
> **I want** to read general metadata of a shared resource (data or service)
> **So that** I can understand better what is the resource and its properties.  

### Scenario: default display (desktop)

**Given that** I am a user of the web portal (authenticated or unauthenticated),
**When** I am on the detail page of a resource, 
**Then** I should see the general metadata of the resources (See mock up)

### Scenario: mobile display (desktop)

**Given that** I am a user of the web portal (authenticated or unauthenticated),
**When** I am on the detail page of a resource, 
**And** I use a mobile device
**Then** I should see the general metadata of the resources on its mobile version (See mock up)

### Scenario : Temporal Coverage

**Given that** I am a user of the web portal (authenticated or unauthenticated) on the detail page of a resource
**When** the metadata `Start date` and `End date`are fulfilled in the ontology,
**Then** I should see `Year of Start Date` - `Year of End Date` (Mock up 1) 
**When** the metadata `Start date` is fulfilled in the ontology and `End Date` is missing
**Then** I should see `From Year of Start Date` (Mock up 2) 
**When** the metadata `End date` is fulfilled in the ontology and `Start Date` is missing
**Then** I should see `To Year of End Date` (Mock up 3) 
**When** Start date and End date are missing
**Then** Temporal Coverage is not displayed at all

### Scenario: Internationalization

**Given that**I am a user of the web portal (authenticated or unauthenticated),
**When** the selected language is English
**Then** texts should be displayed in English language,
`Format`
`Topic`
`Licence`
`Geographical coverage`
`Temporal coverage`
**And** metadata of the resources should be displayed in English

**Given that** I am a user of the web portal on the home page,
**When** the selected language is French
**Then** texts should be displayed in French language,
`Format`
`Domaine`
`Licence`
`Couverture géographique`
`Couverture temporelle`
**And** metadata of the resources should be displayed in French 

**Given that** I am a user of the web portal on the home page,
**When** the selected language is German
**Then** texts should be displayed in German language,
`Format`
`Thema`
`Lizenz`
`Geografischer Geltungsbereich`
`Zeitlicher Geltungsbereich`
**And** metadata of the resources should be displayed in German

#### Desktop : 

Dataset : 
1/
![image](https://user-images.githubusercontent.com/92780073/228906912-3cb11aad-d58f-4496-ae2c-6ebefeeabb4b.png)

2/ 
<img width="492" alt="image" src="https://user-images.githubusercontent.com/92780073/229084164-090712db-eb0d-42b9-a006-5caa1a40e776.png">

3/ 
<img width="515" alt="image" src="https://user-images.githubusercontent.com/92780073/229084351-c58b945e-e7b1-4812-9e3a-43530eb46d12.png">

Service 
![image](https://user-images.githubusercontent.com/92780073/228907029-26f87303-be87-4d13-b7f8-b5626efdcba3.png)

#### Mobile : 
![image](https://user-images.githubusercontent.com/92780073/228907401-2f70adad-1bae-4820-82f2-eb4e2ad909cd.png)

### Environment

- staging URL: <https://app.staging.okp4.network/>

## Additional informations

None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206531451) by [Unito](https://www.unito.io)

**Comment by MdechampG** [comment]
@0xLodz I could not finalize the spec for the temporal coverage. 
For now I propose you to show only the year of the start date and the year of the end date. 

![image](https://user-images.githubusercontent.com/92780073/228907666-0990556a-8fe8-447f-ab24-dfd38a02e316.png)


It's not ideal for this dataset but I will create a new issue next week. 

For now, don't consider the case where one date in not specified. I will handle it in the new issue. 

Please tell me if you have any questions. 

Thank you :)

**Comment by 0xLodz** [comment]
Thanks @MdechampG for the details.
After looking at the current [Ontology examples](https://github.com/okp4/ontology/blob/5f9b94907581c9f06a2e1fa0872188339250bf7c/example/rhizome/dataset/65eda3f4-ecb6-4322-90e7-1832ed3178e9.ttl#L30) with the help of the tech team, it appears that Temporal coverage has only a defined start date. We can display the start date and update the component later, according to the ontology spec.

**Comment by ccamel** [comment]
@0xLodz As per the ontology model, [temporal periods](https://github.com/okp4/ontology/blob/5f9b94907581c9f06a2e1fa0872188339250bf7c/src/core.ttl#L80) are defined by both start and end dates, which may be empty. Therefore, it is essential to ensure compliance by considering all possible cases.

**Comment by MdechampG** [comment]
Indeed all `End Dates` are empty in the examples of the ontology. We will change that. 

I would prefer to stay as simple as possible for now as we are going to change the temporal coverage display next week (in a dedicated issue). 

I have added the different cases in the description of the issue.

**Comment by MdechampG** [comment]
Test 06/04/23

Desktop : Firefox, Safari, Chrome
Mobile : Iphone 12 Safari

Scenario: default display (desktop) : OK ✅ 

Scenario: default display (mobile) : OK ✅ 

Scenario : Temporal coverage :x: 
For all datasets and services we only see one date `2022`
We can directly implement the enhancement #169 rather than doing the version described in this issue. 

Scenario: Internationalization : OK ✅

**Comment by 0xLodz** [comment]
We can definitely update Temporal Coverage date it in the next iteration, with the issue #169
