### ISSUE TITLE
Feat : General description for a Dataspace

### ISSUE THREAD

**Issue by henigh** [okp4/dataverse-portal#71]
# Feature: General description for a Data Space

> **As a** user of the portal,
> **I want** to see a Data Space description 
> **So that** I can check out the purpose of the Data Space before joining it.

### Scenario: default display (desktop)

**Given that** I am a user of the web portal (unauthenticated or authenticated),
**And** I am using a *desktop* device,
**When** I am on the Data Space detail page 
**Then** I should see the title of the Data Space, its label (Data Space) and a proper description that appear as presented in the mockup below

### Scenario : Mobile Display
**Given that** I am a user of the web portal (authenticated or unauthenticated),
**When** I am on a Data Space detail page
**And** I use a mobile device
**Then** I should see mobile friendly display (See mock up)

### Scenario : Internationalization
**Given that** I am a user of the web portal (authenticated or unauthenticated),
**When** the selected language is English, French, or German
**Then** the `metadata` should be displayed in the adequate selected language (See config)

## Resources

Ontology examples : https://github.com/okp4/ontology/tree/main/example/rhizome

### Mockups

Desktop. 

![image.png](https://images.zenhubusercontent.com/617955902b89e7481066da3f/8b74ec30-6f91-43e8-8000-23ebbfc30484)

### Mobile
<img width="251" alt="image" src="https://user-images.githubusercontent.com/39368385/223369700-00c09aa1-fe5f-44cc-8962-ff5dd92e2c8b.png">

### Environment

- staging URL: <https://app.staging.okp4.network/>

## Additional informations

None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206531549) by [Unito](https://www.unito.io)

**Comment by MdechampG** [comment]
Test 07/04
Desktop : Firefox and Safari 
Mobile : Safari

Scenario : Default Display : OK ✅ 

Scenario : Mobile Display : OK ✅ 

Scenario : Internationalization: OK ✅ 
Nb : Impossible to test the internationalization of the metadata as the ontology is not yet connected.
