### ISSUE TITLE
Feat : Governance description for a Data Space

### ISSUE THREAD

**Issue by henigh** [okp4/dataverse-portal#72]
# Feature: Governance description for a Data Space
> **As a** user of the portal,
> **I want** to see a Data Space Governance description 
> **So that** I can quickly check out governance mainlines 

### Scenario 1 : default display (desktop)
**Given that** I am a user of the web portal (unauthenticated or authenticated),
**And** I am using a _desktop_ device,
**When** I am on the Data Space detail page 
**Then** I should see a proper description for the resource governance (Data Space in this particular case) that appears as presented in the mockup below

### Scenario 2 : Access governance button
**Given that** I am a user of the web portal (unauthenticated or authenticated),
**And** I am using a _desktop_ device,
**Then** the button 'See Governance' is disabled

### Scenario 3 : Mobile Display
Given that I am a user of the web portal (authenticated or unauthenticated),
When I am on Data Space detail page 
And I use a mobile device
Then I should see mobile friendly display (See mock up)

### Scenario 4 : Internationalization
**Given that** I am a user of the web portal (authenticated or unauthenticated),
**When** the selected language is **English**, **French**, or **German**
**Then**`title`,  `description` and `button` should be displayed in the adequate selected language _(See config)_

## Config example
As the dedicated service to fetch the Data Space governance description from the blockchain is not ready yet, here is the description for 2 Data Spaces:

### DS4I Data Space
**En**
> Governance _(title)_
> DS4I is a private Data Space where resources are only accessible for a group of addresses contained in a dedicated whitelist.
> Only OKP4 have the authority to edit the Whitelist. _(description)_
> Access governance _(button)_

**Fr**
> Gouvernance _(title)_
> DS4I est un Data Space privé où les ressources ne sont accessibles que pour un groupe
> d'adresses de wallets contenues dans une Whitelist dédiée.
> Seul OKP4 a le droit de modifier cette whitelist. _(description)_
> Accéder à la governance _(button)_

**DE**
> Führung  _(title)_
> DS4I ist ein privater Data Space, in dem die Ressourcen nur für eine Gruppe zugänglich sind.
> Adressen von Wallets, die in einer dedizierten Whitelist enthalten sind.
> Nur OKP4 hat das Recht, diese Whitelist zu ändern. _(description)_
> Auf Governance zugreifen _(button)_

### Rhizome
**En**

> This first Data Space has a centralized governance: only OKP4 can modify the rules.
> In this first version, only OKP4 can register data and services. 
> However, any wallet is allowed to download data. 

**Fr**

> Ce premier Data Space a une gouvernance centralisée : seul OKP4 peut modifier les règles.
> Dans cette première version, seul OKP4 peut enregistrer des données et des services. 
> Toutefois, n'importe quel wallet est autorisé à télécharger les données. 

**De**

> Dieser erste Data Space hat eine zentralisierte Governance: Nur OKP4 kann die Regeln ändern.
> In dieser ersten Version kann nur OKP4 Daten und Dienste speichern. 
> Allerdings ist es jeder Wallet erlaubt, Daten hochzuladen.

### Mockups
Desktop. 

![image.png](https://images.zenhubusercontent.com/617955902b89e7481066da3f/e2af4d3d-aa33-429f-b290-f163688f60f4)

Mobile
![](https://user-images.githubusercontent.com/39368385/222469076-6e3fac26-38bd-43a9-bb72-56478db4c1c5.png)

### Environment

* staging URL: <https://app.staging.okp4.network/>

## Additional informations
None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206531612) by [Unito](https://www.unito.io)

**Comment by MdechampG** [comment]
Test 07/04
Desktop : Safari, Firefox
Mobile : Safari

Scenario 1 : default display (desktop) OK ✅ 

Scenario 2 : Access governance button OK ✅ 

Scenario 3 : Mobile Display OK ✅ 

Scenario 4 : Internationalization OK ✅
