### ISSUE TITLE
Feat : Data Spage page - number of datasets

### ISSUE THREAD

**Issue by henigh** [okp4/dataverse-portal#83]
# Feature: Dataset card - number of datasets & update

> **As a** user on the portal, unauthenticated or not
> **I want** to know the number of datasets, and the last deposit (update) in a particular data space
> **So that** I can know the "size" of the data space in terms of dataset resources, and how often it is updated

### Scenario: Default display

**Given that** I am a user of the portal 
**And** I am using any device,
**When** I am on data space page
**Then** I should see the title of the component 
**And** number of datasets, and last deposit should appear as presented in the mockup

### Scenario : Internationalization

**Given that** I am a user of the web portal on a Data Space details page,
**When** the selected language is **English**
**Then** texts should be displayed in English language,
`In this Data Space`
`Datasets`
`Last update`
**And** the date should be displayed like : Oct 29 2022

**Given that** I am a user of the web portal on a Data Space details page,
**When** the selected language is **French**
**Then** texts should be displayed in **French** language,
`Dans ce Data Space`
`Jeux de données`
`Dernière mise à jour`
**And** the date should be displayed like : 29 Oct 2022

**Given that** I am a user of the web portal on a Data Space details page,
**When** the selected language is **German**
**Then** texts should be displayed in **German** language,
`In diesem Data Space`
`Datensätze`
`Letzte Aktualisierung`
**And** the date should be displayed like : 29 Okt 2022

## Technical specifications : 

Evolution of the component : please note that 2 buttons will be integrated in this card. You can see the mock up on the Figma. 

Number of datasets 
Number if datasets should be fetched from ontology

Last update
Last Update value (as date) should be fetched from ontology

## Config 1 : Number of Services 
While ontology is in progress, Datasets number are : 
- Rhizome : 20
- DS4I : 1

## Config 2 : Last update
While ontology is in progress, last update is 
- DS4I : 25/03/2023
- Rhizome : 28/03/2023

### Mockups
Desktop

![image.png](https://images.zenhubusercontent.com/617955902b89e7481066da3f/aa8a4322-7fd3-45ca-a0f8-703fc7fe8b76)

Mobile

![image.png](https://images.zenhubusercontent.com/617955902b89e7481066da3f/6d02b4cf-9f3d-4fae-be23-42fe7dafbc30)

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206541864) by [Unito](https://www.unito.io)

**Comment by ErikssonJoakim** [comment]
@MdechampG We might as well add the header as well?

![Capture d’écran 2023-04-04 à 13 26 56](https://user-images.githubusercontent.com/75730728/229777668-d63bd47d-9544-4d03-9d20-ad8e6595b960.png)

From what I can see there are no current issues that contain the header feature.
I will need the translations though.

**Comment by MdechampG** [comment]
Well seen @ErikssonJoakim ! 
The issue is updated

**Comment by MdechampG** [comment]
Test 07/04
Desktop : Safari, Firefox
Mobile : Safari 

Scenario: Default display OK ✅ 

Scenario : Internationalization OK ✅
