### ISSUE TITLE
Feat : Service card - number of service & update

### ISSUE THREAD

**Issue by henigh** [okp4/dataverse-portal#84]
# Feature: Services card - number of Services & update

> **As a** user on the portal, unauthenticated or not
> **I want** to know the number of Services, and the last deposit (update) in a particular data space
> **So that** I can know the "size" of the data space in terms of Service resources, and how often it is updated

### Scenario: Default display

**Given that** I am a user of the portal 
**And** I am using any device,
**When** I am on data space page
**Then** number of Services, and last deposit should appear as presented in the mockup

### Scenario : Internationalization

**Given that** I am a user of the web portal on a Data Space details page,
**When** the selected language is **English**
**Then** texts should be displayed in English language,
`Services`
`Last update`
**And** the date should be displayed like : Oct 29 2022

**Given that** I am a user of the web portal on a Data Space details page,
**When** the selected language is **French**
**Then** texts should be displayed in **French** language,
`Services`
`Dernière mise à jour`
**And** the date should be displayed like : 29 Oct 2022

**Given that** I am a user of the web portal on a Data Space details page,
**When** the selected language is **German**
**Then** texts should be displayed in **German** language,
`Dienste`
`Letzte Aktualisierung`
**And** the date should be displayed like : 29 Okt 2022

## Technical specifications

Evolution of the component : please note that 2 buttons will be integrated in this card. You can see the mock up on the Figma.

Number of datasets
Number if datasets should be fetched from ontology

Last update
Last Update value (as date) should be fetched from ontology

## Config 1 : Number of Services 
While ontology is in progress, Services number are : 
- Rhizome : 7
- DS4I : 1

## Config 2 : Last update
While ontology is in progress, last deposit is 
- DS4I : 02/04/2023
- Rhizome : 31/03/2023

### Mockups
Desktop
![image.png](https://images.zenhubusercontent.com/617955902b89e7481066da3f/e779e3dc-bb74-4f2b-817b-db6f3ff9956e)

Mobile

![image.png](https://images.zenhubusercontent.com/617955902b89e7481066da3f/9a79b0f0-915b-4632-a173-1711dd23d467)

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206541952) by [Unito](https://www.unito.io)

**Comment by MdechampG** [comment]
Test 07/04
Desktop : Safari, Firefox
Mobile : Safari 

Scenario: Default display OK ✅ 

Scenario : Internationalization OK ✅
