### ISSUE TITLE
Feat : Data Space Detail Page – tags 

### ISSUE THREAD

**Issue by henigh** [okp4/dataverse-portal#86]
# Feat : Data Space Detail Page – tags 

> **As a** user of the portal,
> **I want** to check Sata Space related tags
> **So that** I can quickly understand what this Data Space is about

### Scenario: default display (desktop)

**Given that** I am a user of the web portal (authenticated or unauthenticated),
**When** I am on the detail page of a Data Space, 
**Then** I should see the related tags appear as presented in the mockup

### Scenario: mobile display (desktop)

**Given that** I am a user of the web portal (authenticated or unauthenticated),
**When** I am on the detail page of a Data Space, 
**And** I use a mobile device
**Then** I should see the related tags appear in a mobile friendly display

## Technical Specifications
Tags should be fetched from ontology 
Tags can contain text on 2 lines maximum, with an ellipsis in case of longer text (same behavior as Chips)

### Mockups
Desktop : 
![image.png](https://images.zenhubusercontent.com/617955902b89e7481066da3f/f1cae478-5a8e-4328-86f7-3c6b3ebeba9a)

Mobile : 
![image.png](https://images.zenhubusercontent.com/617955902b89e7481066da3f/734e1ab4-f8e0-4448-a698-c1b7ee0eefb3)

### Environment

- staging URL: <https://app.staging.okp4.network/>

## Additional informations

None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206541976) by [Unito](https://www.unito.io)

**Comment by MdechampG** [comment]
Test 06/04/23

Desktop : Firefox, Safari, Chrome
Mobile : Safari (iPhone 12)

Scenario : general display (desktop) : OK ✅ 
Note : I can't test when the tag is long with these faked data -> To test with the ontology connected

Scenario : mobile display : OK ✅ 

Thanks @0xLodz !

**Comment by MdechampG** [comment]
You're right :) It's good thank you ! 

![image](https://user-images.githubusercontent.com/92780073/230345908-0a825890-4a92-48bb-b60d-d0ceae33e0cd.png)
