### ISSUE TITLE
Feat : Data Space Detail Page – topics

### ISSUE THREAD

**Issue by henigh** [okp4/dataverse-portal#87]
# Feat : Data Space Detail Page – topics 

> **As a** user of the portal,
> **I want** to check the topics related to one Data Space
> **So that** I can quickly understand what this Data Space is about (topics covered by the Data Space)

### Scenario: default display (desktop)

**Given that** I am a user of the web portal (authenticated or unauthenticated),
**When** I am on the detail page of a Data Space, 
**Then** I should see the related topics appear as presented in the mockup

### Scenario: mobile display (desktop)

**Given that** I am a user of the web portal (authenticated or unauthenticated),
**When** I am on the detail page of a Data Space, 
**And** I use a mobile device
**Then** I should see the related topics appears in a mobile friendly display

### Scenario: Internationalization
Topics should appear **correctly** regarding the selected language.

**EN**

> - Agriculture, Food, environment and forestry.
> - Biology, geology, and chemistry
> - Industry, mobility, and engineering
> - Logistics, retail, supply chain, and eCommerce
> - DeFi and Crypto
> - Healthcare
> - Business and purchase
> - Marketing and Customer Behavior
> - Energy
> - Other

**FR**
> - Agriculture, alimentation, environnement et foresterie.
> - Biologie, géologie et chimie
> - Industrie, mobilité et ingénierie
> - Logistique, commerce de détail, chaîne d'approvisionnement et eCommerce
> - Crypto et finance décentralisée
> - Soins de santé
> - Commerce et approvisionnement 
> - Marketing et comportement des clients
> - Énergie
> - Autres

**GR**
> - Landwirtschaft, Ernährung, Umwelt und Forstwirtschaft
> - Biologie, Geologie und Chemie
> - Industrie, Mobilität und Technik
> - Logistik, Einzelhandel, Lieferkette und eCommerce
> - DeFi und Krypto
> - Gesundheitswesen
> - Wirtschaft und Einkauf
> - Marketing und Kundenverhalten
> - Energie
> - Sonstiges

## Technical Specifications
topics should be fetched from ontology 

### Mockups
Desktop : 
![image.png](https://images.zenhubusercontent.com/617955902b89e7481066da3f/bbc0cbf2-33f1-4cac-8b3d-ef9aace289d0)

Mobile : 
![image.png](https://images.zenhubusercontent.com/617955902b89e7481066da3f/15c88b4e-587a-4cd1-bf55-b1fc420d8d41)

### Environment

- staging URL: <https://app.staging.okp4.network/>

## Additional informations

None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206542017) by [Unito](https://www.unito.io)

**Comment by MdechampG** [comment]
Test 06/04/23

Desktop : Firefox, Safari, Chrome
Mobile : Iphone 12 Safari

Scenario: default display (desktop) : OK ✅ 

Scenario: default display (mobile) : OK ✅ 

Scenario: Internationalization : : OK ✅
