### ISSUE TITLE
Feat : catalog grid content

### ISSUE THREAD

**Issue by MdechampG** [okp4/dataverse-portal#96]
# Feature: Catalog grid content

> **As a** user of the portal on the catalog 
> **I want** to see all the resources of the catalog
> **So that** I can explore the dataverse   

### Scenario: default display (desktop)
    
**Given that** I am a user of the web portal,
**When** I am on the catalog page (authenticated or unauthenticated)
**Then** I should see 20 cards of dataverse items displayed in a 4-column grid (see mock up) without any filter
**And** each card should be labelled according to the type (Data space, Dataset, Service)
**And** each card contains the `title` and the `topic` (for data spaces and datasets) or the `category` (for services)
**And** cards are sorted ‘by date of last update’
**When** I scroll down 
**Then** the resources load 20 by 20 (infinite scroll, load as you go)

### Scenario: Internationalization

**Given that** I am a user of the web portal on the catalog page,
**When** the selected language is English
**Then** metadata of the resources (title and category) should be displayed in English

**Given that** I am a user of the web portal on the home page,
**When** the selected language is French
**Then** metadata of the resources (title and category) should be displayed in French if available or English by default

**Given that** I am a user of the web portal on the home page,
**When** the selected language is German
**Then** metadata of the resources (title and category) should be displayed in German if available or English by default

## Requirements

The content should be fetched from the ontological database. 

### Mockups

Mock up  : 
![image](https://user-images.githubusercontent.com/92780073/228203366-cd6b680f-d99a-453a-8b23-60725523c675.png)

### Environment

- staging URL: <https://app.staging.okp4.network/>

## Additional informations

None.

**Comment by fredericvilcot** [comment]
@MdechampG @ChaimaaZaoui 
To update the views and implement the "infinite scroll" mechanism, I need two elements:

- a loader under the cards in the `dataverse` view to indicate to the user that more cards are loading
- how do we sort the dataverse? For now we could sort by: `type`, `title` or `description`. Please tell me.

Thx

**Comment by ChaimaaZaoui** [comment]
@fredericvilcot 

- I'll work on the loader with lisa asap and give you its UX
- The order on the dataverse should be following the alphabetical order of titles

**Comment by ChaimaaZaoui** [comment]
@fredericvilcot regarding the loader here is its design :
https://user-images.githubusercontent.com/115076387/233094531-cbea7bf8-2983-497a-bf96-815b9372eeda.mov

and here the file:
[loader.json.zip](https://github.com/okp4/product-kanban/files/11273725/loader.json.zip)

**Comment by ChaimaaZaoui** [comment]
@ccamel or @amimart can one of you please test if the order in is good. That way I can close the ticket. Thank you.

**Comment by MdechampG** [comment]
Test on the sort of cards failed :x: it is sorted by alphabetical order and not by date of last update, implying that it's not the same order according to the language. 

<img width="1146" alt="image" src="https://github.com/okp4/dataverse-portal/assets/92780073/54d4fe89-465e-4fda-bff3-73da180c00cc">

<img width="1127" alt="image" src="https://github.com/okp4/dataverse-portal/assets/92780073/a2f1ddfe-45f2-4a86-9e65-3f9829434982">

**Comment by fredericvilcot** [comment]
@MdechampG 
I will make the changes as requested.
FYI, I implemented this comment: https://github.com/okp4/dataverse-portal/issues/96#issuecomment-1511538466

**Comment by fredericvilcot** [comment]
@MdechampG 
Sure, let me know if I have to make modifications after your discussion with @ChaimaaZaoui .

**Comment by ChaimaaZaoui** [comment]
All good, we keep the alphabetical order
