### ISSUE TITLE
Feat: See details of a resource

### ISSUE THREAD

**Issue by MdechampG** [okp4/dataverse-portal#97]
# Feature: See details of a resource
> **As a** user of the portal on the catalog 
> **I want** to click on `See details`
> **So that** I can have more information about a resource registered in the Dataverse

### Scenario: default display (desktop)
**Given that** I am a user of the web portal on the home page,
**When** I click on ‘See details’ button of a resource
**Then** I should be redirected to the resource details page of this resource (See requirements)
**And** I should see an arrow to go on Dataverse page

## Requirements
The URL of the resource detail page should be with the framework : 
Data space : `/dataverse/dataspace/ID`
Dataset : `/dataverse/dataset/ID`
Service : `/dataverse/service/ID`

### Mockups
Mock up  : 
![image.png](https://images.zenhubusercontent.com/616e76157d9dbb44e290ed55/242dbd7d-998d-4b10-8605-13c2044e190f)

![image](https://user-images.githubusercontent.com/92780073/228909276-f4d2f9e9-8a49-4d47-9ac6-6b74cec973f4.png)

### Environment

* staging URL: <https://app.staging.okp4.network/>

## Additional informations
None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206542387) by [Unito](https://www.unito.io)

**Comment by ccamel** [comment]
@MdechampG it would be advisable to specify the behavior if the text to be displayed is very long (both for the title and the description) - we display everything, we cut, we ellipse...

**Comment by MdechampG** [comment]
@lolottetheclash I have added the spec about the previous page arrow. I put this issue in `To Do` as discussed :)

**Comment by 0xLodz** [comment]
@lolottetheclash @MdechampG should we display `Dataverse` according to the mockup ?
![image](https://user-images.githubusercontent.com/8344874/230043068-9313fedc-88a9-4793-84d2-6ee1980d2123.png)
Or will it be done later?

**Comment by MdechampG** [comment]
This new feature is in this issue : https://github.com/okp4/dataverse-portal/issues/168

**Comment by MdechampG** [comment]
Test 07/04
Desktop : Safari, Firefox
Mobile : Safari

Scenario: default display (desktop) OK ✅
